# src/big_earth_net/analyze_large_favela_upper_bound_224.py

"""
Large-favela upper-bound diagnostic for reBEN/UPerNet favela segmentation.

Purpose
-------
This script evaluates the already-trained baseline on progressively easier
subsets of patches, selected by ground-truth favela density.

It answers:

    At what favela-density threshold does the model become reliable?

The script reads per-patch metrics generated by:

    src/big_earth_net/visualize_reben_predictions_224.py

Expected input files:

    <run-dir>/visual_predictions/train_best_thr0p450/per_patch_metrics_train.csv
    <run-dir>/visual_predictions/val_best_thr0p450/per_patch_metrics_val.csv
    <run-dir>/visual_predictions/test_best_thr0p450/per_patch_metrics_test.csv

Main outputs:

    <run-dir>/large_favela_upper_bound_224/
        large_favela_upper_bound_report.md
        metadata.json
        csv/
            large_favela_upper_bound_by_split.csv
            large_favela_upper_bound_by_region.csv
            large_favela_upper_bound_by_city.csv
            large_favela_upper_bound_enriched_per_patch.csv
        figures/
            upper_bound_iou_by_threshold.png
            upper_bound_dice_by_threshold.png
            upper_bound_precision_by_threshold.png
            upper_bound_recall_by_threshold.png
            upper_bound_pred_minus_gt_by_threshold.png
            upper_bound_patch_count_by_threshold.png
            upper_bound_mean_gt_pred_by_threshold_<split>.png
            upper_bound_city_iou_gt10_<split>.png
            upper_bound_city_iou_gt20_<split>.png

Author: Mahmoud Abo Shukr
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


DEFAULT_SPLITS = ["train", "val", "test"]

SUBSET_DEFINITIONS = [
    ("all", None),
    ("positive_gt0", 0.0),
    ("gt1", 1.0),
    ("gt5", 5.0),
    ("gt10", 10.0),
    ("gt20", 20.0),
    ("gt40", 40.0),
]

SUBSET_LABELS = {
    "all": "All patches",
    "positive_gt0": "Positive patches",
    "gt1": "GT > 1%",
    "gt5": "GT > 5%",
    "gt10": "GT > 10%",
    "gt20": "GT > 20%",
    "gt40": "GT > 40%",
}

SUBSET_ORDER = [name for name, _ in SUBSET_DEFINITIONS]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze large-favela upper-bound performance from per-patch metrics."
    )

    parser.add_argument(
        "--run-dir",
        type=Path,
        required=True,
        help=(
            "Experiment run directory containing visual_predictions/<split>_best_thr*/"
            "per_patch_metrics_<split>.csv"
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory. Default: <run-dir>/large_favela_upper_bound_224",
    )

    parser.add_argument(
        "--splits",
        nargs="+",
        default=DEFAULT_SPLITS,
        help="Splits to process. Default: train val test",
    )

    parser.add_argument(
        "--threshold-tag",
        type=str,
        default="best_thr0p450",
        help=(
            "Preferred visual_predictions folder suffix. Default: best_thr0p450. "
            "The script also searches automatically if this exact folder is absent."
        ),
    )

    parser.add_argument(
        "--min-city-patches",
        type=int,
        default=5,
        help=(
            "Minimum number of patches required to include a city in city-level plots. "
            "Default: 5"
        ),
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite output directory if it exists.",
    )

    return parser.parse_args()


def prepare_output_dir(output_dir: Path, overwrite: bool) -> None:
    if output_dir.exists():
        if not overwrite:
            raise FileExistsError(
                f"Output directory already exists:\n"
                f"  {output_dir}\n"
                f"Use --overwrite to replace it."
            )
        shutil.rmtree(output_dir)

    (output_dir / "csv").mkdir(parents=True, exist_ok=True)
    (output_dir / "figures").mkdir(parents=True, exist_ok=True)


def find_metrics_csv(run_dir: Path, split: str, threshold_tag: str) -> Path:
    visual_root = run_dir / "visual_predictions"

    direct_candidates = [
        visual_root / f"{split}_{threshold_tag}" / f"per_patch_metrics_{split}.csv",
        visual_root / f"{split}_best_thr0p450" / f"per_patch_metrics_{split}.csv",
        visual_root / f"{split}_best" / f"per_patch_metrics_{split}.csv",
    ]

    for candidate in direct_candidates:
        if candidate.exists():
            return candidate

    glob_candidates = sorted(
        visual_root.glob(f"{split}_best_thr*/per_patch_metrics_{split}.csv")
    )

    if glob_candidates:
        return glob_candidates[0]

    raise FileNotFoundError(
        f"Could not find per_patch_metrics_{split}.csv under:\n"
        f"  {visual_root}\n"
        f"Expected something like:\n"
        f"  {visual_root}/{split}_best_thr0p450/per_patch_metrics_{split}.csv"
    )


def normalise_required_columns(df: pd.DataFrame, split: str) -> pd.DataFrame:
    df = df.copy()

    rename_candidates = {
        "gt_pos_pct": [
            "gt_pos_pct",
            "gt_favela_pct",
            "label_pos_pct",
            "mask_pos_pct",
            "gt_positive_pct",
        ],
        "pred_pos_pct": [
            "pred_pos_pct",
            "prediction_pos_pct",
            "pred_favela_pct",
            "pred_positive_pct",
        ],
        "iou_favela": [
            "iou_favela",
            "favela_iou",
            "iou",
            "patch_iou_favela",
        ],
        "dice_favela": [
            "dice_favela",
            "favela_dice",
            "dice",
            "patch_dice_favela",
        ],
        "precision_favela": [
            "precision_favela",
            "favela_precision",
            "precision",
        ],
        "recall_favela": [
            "recall_favela",
            "favela_recall",
            "recall",
        ],
        "fp_pct": [
            "fp_pct",
            "false_positive_pct",
        ],
        "fn_pct": [
            "fn_pct",
            "false_negative_pct",
        ],
    }

    for standard_name, possible_names in rename_candidates.items():
        if standard_name in df.columns:
            continue

        for candidate in possible_names:
            if candidate in df.columns:
                df = df.rename(columns={candidate: standard_name})
                break

    required = ["gt_pos_pct", "pred_pos_pct"]
    missing = [col for col in required if col not in df.columns]

    if missing:
        raise ValueError(
            f"Missing required columns in split={split}: {missing}\n"
            f"Available columns:\n{list(df.columns)}"
        )

    if "split" not in df.columns:
        df["split"] = split
    else:
        df["split"] = df["split"].fillna(split)

    if "city" not in df.columns:
        df["city"] = "unknown_city"

    if "region" not in df.columns:
        df["region"] = "unknown_region"

    if "patch_id" not in df.columns:
        df["patch_id"] = [f"{split}_patch_{i:06d}" for i in range(len(df))]

    numeric_cols = [
        "gt_pos_pct",
        "pred_pos_pct",
        "iou_favela",
        "dice_favela",
        "precision_favela",
        "recall_favela",
        "fp_pct",
        "fn_pct",
    ]

    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    df["gt_pos_pct"] = df["gt_pos_pct"].fillna(0.0).clip(0.0, 100.0)
    df["pred_pos_pct"] = df["pred_pos_pct"].fillna(0.0).clip(0.0, 100.0)

    return df


def add_confusion_percentages(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add TP/FP/FN/TN percentages per patch.

    Since all patches have the same spatial size, summing percentages across
    patches is equivalent to summing pixel counts up to a constant factor.

    Priority:
        1. Use existing fp_pct/fn_pct if present.
        2. Infer TP from IoU, GT %, and Pred %.
        3. Fall back to min(GT, Pred) approximation.
    """

    df = df.copy()

    gt = df["gt_pos_pct"].fillna(0.0).clip(0.0, 100.0)
    pred = df["pred_pos_pct"].fillna(0.0).clip(0.0, 100.0)

    if "fp_pct" in df.columns and "fn_pct" in df.columns:
        fp = df["fp_pct"].fillna(0.0).clip(0.0, 100.0)
        fn = df["fn_pct"].fillna(0.0).clip(0.0, 100.0)
        tp = (gt - fn).clip(0.0, 100.0)
    elif "iou_favela" in df.columns:
        iou = df["iou_favela"].fillna(0.0).clip(0.0, 1.0)

        # IoU = TP / (GT + Pred - TP)
        # TP = IoU * (GT + Pred) / (1 + IoU)
        tp = (iou * (gt + pred) / (1.0 + iou)).fillna(0.0).clip(0.0, 100.0)
        fp = (pred - tp).clip(0.0, 100.0)
        fn = (gt - tp).clip(0.0, 100.0)
    else:
        tp = np.minimum(gt, pred)
        fp = (pred - tp).clip(0.0, 100.0)
        fn = (gt - tp).clip(0.0, 100.0)

    tn = (100.0 - tp - fp - fn).clip(0.0, 100.0)

    df["tp_pct"] = tp
    df["fp_pct"] = fp
    df["fn_pct"] = fn
    df["tn_pct"] = tn

    return df


def read_all_splits(
    run_dir: Path,
    splits: Sequence[str],
    threshold_tag: str,
) -> Tuple[pd.DataFrame, Dict[str, str]]:
    frames: List[pd.DataFrame] = []
    paths: Dict[str, str] = {}

    for split in splits:
        csv_path = find_metrics_csv(run_dir, split, threshold_tag=threshold_tag)
        paths[split] = str(csv_path)

        df = pd.read_csv(csv_path)
        df = normalise_required_columns(df, split=split)
        df = add_confusion_percentages(df)

        frames.append(df)

    all_df = pd.concat(frames, ignore_index=True)
    return all_df, paths


def safe_div(num: float, den: float) -> float:
    if den == 0:
        return 0.0
    return float(num / den)


def subset_mask(df: pd.DataFrame, subset_name: str, threshold: Optional[float]) -> pd.Series:
    if subset_name == "all":
        return pd.Series(True, index=df.index)

    if subset_name == "positive_gt0":
        return df["gt_pos_pct"] > 0.0

    assert threshold is not None
    return df["gt_pos_pct"] > threshold


def aggregate_metrics(
    df: pd.DataFrame,
    group_cols: Sequence[str],
) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    if len(df) == 0:
        return pd.DataFrame()

    if group_cols:
        grouped = df.groupby(list(group_cols), dropna=False, observed=True)
        iterator = grouped
    else:
        iterator = [((), df)]

    for keys, group in iterator:
        if not isinstance(keys, tuple):
            keys = (keys,)

        row: Dict[str, object] = {}

        for col, key in zip(group_cols, keys):
            row[col] = key

        tp = float(group["tp_pct"].sum())
        fp = float(group["fp_pct"].sum())
        fn = float(group["fn_pct"].sum())
        tn = float(group["tn_pct"].sum())

        row["n_patches"] = int(len(group))

        row["global_iou_favela"] = safe_div(tp, tp + fp + fn)
        row["global_dice_favela"] = safe_div(2.0 * tp, 2.0 * tp + fp + fn)
        row["global_precision_favela"] = safe_div(tp, tp + fp)
        row["global_recall_favela"] = safe_div(tp, tp + fn)

        row["global_iou_no_favela"] = safe_div(tn, tn + fp + fn)
        row["global_accuracy"] = safe_div(tp + tn, tp + fp + fn + tn)

        row["mean_gt_pos_pct"] = float(group["gt_pos_pct"].mean())
        row["median_gt_pos_pct"] = float(group["gt_pos_pct"].median())
        row["mean_pred_pos_pct"] = float(group["pred_pos_pct"].mean())
        row["median_pred_pos_pct"] = float(group["pred_pos_pct"].median())
        row["mean_pred_minus_gt_pct"] = (
            row["mean_pred_pos_pct"] - row["mean_gt_pos_pct"]
        )

        row["total_gt_pos_pct_sum"] = float(group["gt_pos_pct"].sum())
        row["total_pred_pos_pct_sum"] = float(group["pred_pos_pct"].sum())

        if "iou_favela" in group.columns:
            row["patch_mean_iou_favela"] = float(group["iou_favela"].mean())
            row["patch_median_iou_favela"] = float(group["iou_favela"].median())

        if "dice_favela" in group.columns:
            row["patch_mean_dice_favela"] = float(group["dice_favela"].mean())
            row["patch_median_dice_favela"] = float(group["dice_favela"].median())

        rows.append(row)

    return pd.DataFrame(rows)


def build_upper_bound_tables(all_df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    split_rows: List[pd.DataFrame] = []
    region_rows: List[pd.DataFrame] = []
    city_rows: List[pd.DataFrame] = []

    for subset_name, threshold in SUBSET_DEFINITIONS:
        mask = subset_mask(all_df, subset_name, threshold)
        subset_df = all_df[mask].copy()

        if len(subset_df) == 0:
            continue

        by_split = aggregate_metrics(subset_df, ["split"])
        by_split["subset"] = subset_name
        by_split["subset_label"] = SUBSET_LABELS[subset_name]
        by_split["gt_threshold_pct"] = threshold if threshold is not None else np.nan
        split_rows.append(by_split)

        by_region = aggregate_metrics(subset_df, ["split", "region"])
        by_region["subset"] = subset_name
        by_region["subset_label"] = SUBSET_LABELS[subset_name]
        by_region["gt_threshold_pct"] = threshold if threshold is not None else np.nan
        region_rows.append(by_region)

        by_city = aggregate_metrics(subset_df, ["split", "region", "city"])
        by_city["subset"] = subset_name
        by_city["subset_label"] = SUBSET_LABELS[subset_name]
        by_city["gt_threshold_pct"] = threshold if threshold is not None else np.nan
        city_rows.append(by_city)

    split_table = pd.concat(split_rows, ignore_index=True) if split_rows else pd.DataFrame()
    region_table = pd.concat(region_rows, ignore_index=True) if region_rows else pd.DataFrame()
    city_table = pd.concat(city_rows, ignore_index=True) if city_rows else pd.DataFrame()

    for table in [split_table, region_table, city_table]:
        if not table.empty:
            table["subset"] = pd.Categorical(
                table["subset"],
                categories=SUBSET_ORDER,
                ordered=True,
            )
            table["subset_label"] = pd.Categorical(
                table["subset_label"],
                categories=[SUBSET_LABELS[name] for name in SUBSET_ORDER],
                ordered=True,
            )
            table.sort_values(
                [col for col in ["split", "subset", "region", "city"] if col in table.columns],
                inplace=True,
            )

    return split_table, region_table, city_table


def grouped_bar_plot(
    df: pd.DataFrame,
    x_col: str,
    y_col: str,
    group_col: str,
    x_order: Sequence[str],
    title: str,
    ylabel: str,
    out_path: Path,
    rotation: int = 30,
) -> None:
    plot_df = df.copy()
    plot_df[x_col] = plot_df[x_col].astype(str)

    pivot = plot_df.pivot_table(
        index=x_col,
        columns=group_col,
        values=y_col,
        aggfunc="first",
        observed=False,
    )

    pivot = pivot.reindex(list(x_order))

    groups = list(pivot.columns)
    x = np.arange(len(pivot.index))
    n_groups = max(len(groups), 1)
    width = 0.8 / n_groups

    fig_width = max(10, len(x_order) * 1.35)
    fig, ax = plt.subplots(figsize=(fig_width, 5.8))

    for i, group in enumerate(groups):
        values = pivot[group].fillna(0.0).values
        offset = (i - (n_groups - 1) / 2.0) * width
        ax.bar(x + offset, values, width, label=str(group))

    ax.set_title(title)
    ax.set_ylabel(ylabel)
    ax.set_xticks(x)
    ax.set_xticklabels(pivot.index, rotation=rotation, ha="right")
    ax.grid(axis="y", alpha=0.3)
    ax.legend(title=group_col)

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def mean_gt_pred_plot(
    split_table: pd.DataFrame,
    split: str,
    out_path: Path,
) -> None:
    df = split_table[split_table["split"] == split].copy()

    if df.empty:
        return

    df["subset_label"] = df["subset_label"].astype(str)
    df = df.set_index("subset").reindex(SUBSET_ORDER).reset_index()

    x = np.arange(len(df))
    width = 0.38

    fig, ax = plt.subplots(figsize=(10, 5.8))

    ax.bar(
        x - width / 2,
        df["mean_gt_pos_pct"].fillna(0.0).values,
        width,
        label="Mean GT favela %",
    )
    ax.bar(
        x + width / 2,
        df["mean_pred_pos_pct"].fillna(0.0).values,
        width,
        label="Mean predicted favela %",
    )

    labels = [SUBSET_LABELS.get(str(s), str(s)) for s in df["subset"].astype(str)]
    ax.set_title(f"Mean GT vs predicted favela percentage by subset ({split})")
    ax.set_ylabel("Favela pixels (%)")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=30, ha="right")
    ax.grid(axis="y", alpha=0.3)
    ax.legend()

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def city_iou_plot(
    city_table: pd.DataFrame,
    split: str,
    subset_name: str,
    min_city_patches: int,
    out_path: Path,
) -> None:
    df = city_table[
        (city_table["split"] == split)
        & (city_table["subset"].astype(str) == subset_name)
        & (city_table["n_patches"] >= min_city_patches)
    ].copy()

    if df.empty:
        return

    df = df.sort_values("global_iou_favela", ascending=False)

    x = np.arange(len(df))
    fig_width = max(10, len(df) * 0.7)

    fig, ax = plt.subplots(figsize=(fig_width, 5.8))

    ax.bar(x, df["global_iou_favela"].fillna(0.0).values)

    labels = [
        f"{city}\n(n={n})"
        for city, n in zip(df["city"].astype(str), df["n_patches"].astype(int))
    ]

    ax.set_title(
        f"City favela IoU for {SUBSET_LABELS[subset_name]} ({split})\n"
        f"Only cities with at least {min_city_patches} patches"
    )
    ax.set_ylabel("Global favela IoU")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.grid(axis="y", alpha=0.3)

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def save_figures(
    split_table: pd.DataFrame,
    city_table: pd.DataFrame,
    output_dir: Path,
    splits: Sequence[str],
    min_city_patches: int,
) -> None:
    figures_dir = output_dir / "figures"

    x_order = [SUBSET_LABELS[name] for name in SUBSET_ORDER]

    plot_table = split_table.copy()
    plot_table["subset_label"] = plot_table["subset_label"].astype(str)

    grouped_bar_plot(
        df=plot_table,
        x_col="subset_label",
        y_col="global_iou_favela",
        group_col="split",
        x_order=x_order,
        title="Large-favela upper-bound: global favela IoU by subset",
        ylabel="Global favela IoU",
        out_path=figures_dir / "upper_bound_iou_by_threshold.png",
    )

    grouped_bar_plot(
        df=plot_table,
        x_col="subset_label",
        y_col="global_dice_favela",
        group_col="split",
        x_order=x_order,
        title="Large-favela upper-bound: Dice by subset",
        ylabel="Global favela Dice",
        out_path=figures_dir / "upper_bound_dice_by_threshold.png",
    )

    grouped_bar_plot(
        df=plot_table,
        x_col="subset_label",
        y_col="global_precision_favela",
        group_col="split",
        x_order=x_order,
        title="Large-favela upper-bound: precision by subset",
        ylabel="Global favela precision",
        out_path=figures_dir / "upper_bound_precision_by_threshold.png",
    )

    grouped_bar_plot(
        df=plot_table,
        x_col="subset_label",
        y_col="global_recall_favela",
        group_col="split",
        x_order=x_order,
        title="Large-favela upper-bound: recall by subset",
        ylabel="Global favela recall",
        out_path=figures_dir / "upper_bound_recall_by_threshold.png",
    )

    grouped_bar_plot(
        df=plot_table,
        x_col="subset_label",
        y_col="mean_pred_minus_gt_pct",
        group_col="split",
        x_order=x_order,
        title="Prediction minus ground-truth favela percentage by subset",
        ylabel="Mean predicted % - mean GT %",
        out_path=figures_dir / "upper_bound_pred_minus_gt_by_threshold.png",
    )

    grouped_bar_plot(
        df=plot_table,
        x_col="subset_label",
        y_col="n_patches",
        group_col="split",
        x_order=x_order,
        title="Number of patches by upper-bound subset",
        ylabel="Number of patches",
        out_path=figures_dir / "upper_bound_patch_count_by_threshold.png",
    )

    for split in splits:
        mean_gt_pred_plot(
            split_table=split_table,
            split=split,
            out_path=figures_dir / f"upper_bound_mean_gt_pred_by_threshold_{split}.png",
        )

        city_iou_plot(
            city_table=city_table,
            split=split,
            subset_name="gt10",
            min_city_patches=min_city_patches,
            out_path=figures_dir / f"upper_bound_city_iou_gt10_{split}.png",
        )

        city_iou_plot(
            city_table=city_table,
            split=split,
            subset_name="gt20",
            min_city_patches=min_city_patches,
            out_path=figures_dir / f"upper_bound_city_iou_gt20_{split}.png",
        )


def format_float(x: object, digits: int = 4) -> str:
    try:
        if pd.isna(x):
            return ""
        return f"{float(x):.{digits}f}"
    except Exception:
        return str(x)


def make_compact_table_for_report(split_table: pd.DataFrame) -> pd.DataFrame:
    cols = [
        "split",
        "subset_label",
        "n_patches",
        "global_iou_favela",
        "global_dice_favela",
        "global_precision_favela",
        "global_recall_favela",
        "mean_gt_pos_pct",
        "mean_pred_pos_pct",
        "mean_pred_minus_gt_pct",
    ]

    compact = split_table[cols].copy()

    for col in [
        "global_iou_favela",
        "global_dice_favela",
        "global_precision_favela",
        "global_recall_favela",
        "mean_gt_pos_pct",
        "mean_pred_pos_pct",
        "mean_pred_minus_gt_pct",
    ]:
        compact[col] = compact[col].apply(lambda x: format_float(x, digits=4))

    return compact


def create_report(
    output_dir: Path,
    metrics_paths: Dict[str, str],
    split_table: pd.DataFrame,
    region_table: pd.DataFrame,
    city_table: pd.DataFrame,
) -> None:
    report_path = output_dir / "large_favela_upper_bound_report.md"

    lines: List[str] = []

    lines.append("# Large-Favela Upper-Bound Diagnostic")
    lines.append("")
    lines.append("## Objective")
    lines.append("")
    lines.append(
        "This diagnostic evaluates the existing baseline on progressively easier "
        "subsets of patches selected by ground-truth favela density."
    )
    lines.append("")
    lines.append("Main question:")
    lines.append("")
    lines.append("> At what favela-density threshold does the model become reliable?")
    lines.append("")
    lines.append("## Input metric files")
    lines.append("")

    for split, path in metrics_paths.items():
        lines.append(f"- **{split}**: `{path}`")

    lines.append("")
    lines.append("## Subset definitions")
    lines.append("")
    lines.append("| Subset | Definition |")
    lines.append("|:--|:--|")
    lines.append("| All patches | no filtering |")
    lines.append("| Positive patches | ground-truth favela percentage > 0% |")
    lines.append("| GT > 1% | ground-truth favela percentage > 1% |")
    lines.append("| GT > 5% | ground-truth favela percentage > 5% |")
    lines.append("| GT > 10% | ground-truth favela percentage > 10% |")
    lines.append("| GT > 20% | ground-truth favela percentage > 20% |")
    lines.append("| GT > 40% | ground-truth favela percentage > 40% |")

    lines.append("")
    lines.append("## Main split-level results")
    lines.append("")

    compact = make_compact_table_for_report(split_table)
    lines.append(compact.to_markdown(index=False))

    lines.append("")
    lines.append("## Interpretation guide")
    lines.append("")
    lines.append(
        "- If performance improves strongly as GT threshold increases, then large "
        "continuous favela regions are easier and the full task is dominated by "
        "tiny/sparse/ambiguous patches."
    )
    lines.append(
        "- If train improves but validation/test remain weak, then the model is "
        "learning training-city morphology but not generalizing robustly."
    )
    lines.append(
        "- If precision improves but recall drops at high thresholds, the model is "
        "too conservative on large unseen favela regions."
    )
    lines.append(
        "- If predicted favela percentage is much larger than GT percentage, the "
        "model is overpredicting and hard-negative mining is needed."
    )
    lines.append(
        "- If predicted favela percentage is much smaller than GT percentage, the "
        "model is underpredicting and may be missing large labelled regions."
    )

    lines.append("")
    lines.append("## Useful output files")
    lines.append("")
    lines.append("- `csv/large_favela_upper_bound_by_split.csv`")
    lines.append("- `csv/large_favela_upper_bound_by_region.csv`")
    lines.append("- `csv/large_favela_upper_bound_by_city.csv`")
    lines.append("- `csv/large_favela_upper_bound_enriched_per_patch.csv`")
    lines.append("- `figures/upper_bound_iou_by_threshold.png`")
    lines.append("- `figures/upper_bound_precision_by_threshold.png`")
    lines.append("- `figures/upper_bound_recall_by_threshold.png`")
    lines.append("- `figures/upper_bound_pred_minus_gt_by_threshold.png`")

    report_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()

    run_dir: Path = args.run_dir
    output_dir: Path = (
        args.output_dir
        if args.output_dir is not None
        else run_dir / "large_favela_upper_bound_224"
    )

    prepare_output_dir(output_dir, overwrite=args.overwrite)

    all_df, metrics_paths = read_all_splits(
        run_dir=run_dir,
        splits=args.splits,
        threshold_tag=args.threshold_tag,
    )

    split_table, region_table, city_table = build_upper_bound_tables(all_df)

    csv_dir = output_dir / "csv"

    all_df.to_csv(
        csv_dir / "large_favela_upper_bound_enriched_per_patch.csv",
        index=False,
    )

    split_table.to_csv(
        csv_dir / "large_favela_upper_bound_by_split.csv",
        index=False,
    )

    region_table.to_csv(
        csv_dir / "large_favela_upper_bound_by_region.csv",
        index=False,
    )

    city_table.to_csv(
        csv_dir / "large_favela_upper_bound_by_city.csv",
        index=False,
    )

    save_figures(
        split_table=split_table,
        city_table=city_table,
        output_dir=output_dir,
        splits=args.splits,
        min_city_patches=args.min_city_patches,
    )

    metadata = {
        "run_dir": str(run_dir),
        "output_dir": str(output_dir),
        "splits": args.splits,
        "metrics_paths": metrics_paths,
        "subset_definitions": [
            {
                "subset": name,
                "label": SUBSET_LABELS[name],
                "gt_threshold_pct": threshold,
            }
            for name, threshold in SUBSET_DEFINITIONS
        ],
        "min_city_patches": args.min_city_patches,
    }

    with (output_dir / "metadata.json").open("w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    create_report(
        output_dir=output_dir,
        metrics_paths=metrics_paths,
        split_table=split_table,
        region_table=region_table,
        city_table=city_table,
    )

    print("\nDone. Large-favela upper-bound diagnostics written to:")
    print(f"  {output_dir}")

    print("\nMain files:")
    print(f"  {output_dir / 'large_favela_upper_bound_report.md'}")
    print(f"  {output_dir / 'csv' / 'large_favela_upper_bound_by_split.csv'}")
    print(f"  {output_dir / 'csv' / 'large_favela_upper_bound_by_region.csv'}")
    print(f"  {output_dir / 'csv' / 'large_favela_upper_bound_by_city.csv'}")
    print(f"  {output_dir / 'figures'}")

    print("\nSplit-level summary:")
    compact = make_compact_table_for_report(split_table)
    print(compact.to_string(index=False))


if __name__ == "__main__":
    main()