# src/big_earth_net/build_hard_mining_manifest_224.py

"""
Build hard-mining manifests for the reBEN/UPerNet favela segmentation baseline.

Purpose
-------
This script uses the per-patch metrics generated by the visualisation/diagnostic
pipeline to create hard-mining pools for the next training stage.

It creates pools for:

    1. hard negatives
       - low GT favela percentage
       - high predicted favela percentage

    2. missed large positives
       - high GT favela percentage
       - low recall or strong underprediction

    3. good large positives
       - high GT favela percentage
       - good IoU

    4. random negatives
       - no GT favela
       - almost no predicted favela

    5. medium/large positives
       - GT favela percentage >= 5%

Important rule
--------------
Training manifests are built ONLY from the train split to avoid validation/test
leakage. Validation/test pools are exported only for diagnostics.

Expected input files
--------------------
<run-dir>/visual_predictions/train_best_thr0p450/per_patch_metrics_train.csv
<run-dir>/visual_predictions/val_best_thr0p450/per_patch_metrics_val.csv
<run-dir>/visual_predictions/test_best_thr0p450/per_patch_metrics_test.csv

Main outputs
------------
<run-dir>/hard_mining_manifest_224/
    metadata.json
    hard_mining_report.md

    csv/
        all_splits_hard_mining_enriched.csv

        train_hard_negative_strict.csv
        train_hard_negative_moderate.csv
        train_missed_large_positive.csv
        train_severe_missed_large_positive.csv
        train_good_large_positive.csv
        train_medium_large_positive.csv
        train_random_negative.csv

        diagnostic_pool_summary_by_split.csv
        diagnostic_pool_summary_by_split_city.csv

        train_curriculum_manifest_balanced_v1.csv
        train_curriculum_manifest_balanced_v1_unique.csv
        train_curriculum_manifest_conservative_v1.csv
        train_curriculum_manifest_conservative_v1_unique.csv

    figures/
        train_pool_counts.png
        diagnostic_pool_counts_by_split.png
        train_pool_counts_by_city.png
        curriculum_manifest_composition.png

Author: Mahmoud Abo Shukr
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


DEFAULT_SPLITS = ["train", "val", "test"]


POOL_DEFINITIONS = {
    "hard_negative_strict": {
        "description": "gt_pos_pct <= 1 and pred_pos_pct >= 20",
    },
    "hard_negative_moderate": {
        "description": "gt_pos_pct <= 5 and pred_pos_pct >= 10",
    },
    "missed_large_positive": {
        "description": "gt_pos_pct >= 10 and recall_favela < 0.40",
    },
    "severe_missed_large_positive": {
        "description": "gt_pos_pct >= 20 and pred_pos_pct - gt_pos_pct <= -10",
    },
    "good_large_positive": {
        "description": "gt_pos_pct >= 10 and iou_favela >= 0.50",
    },
    "medium_large_positive": {
        "description": "gt_pos_pct >= 5",
    },
    "random_negative": {
        "description": "gt_pos_pct == 0 and pred_pos_pct <= 1",
    },
}


TRAIN_POOL_EXPORTS = [
    "hard_negative_strict",
    "hard_negative_moderate",
    "missed_large_positive",
    "severe_missed_large_positive",
    "good_large_positive",
    "medium_large_positive",
    "random_negative",
]


CURRICULUM_RECIPES = {
    "balanced_v1": {
        "medium_large_positive": 0.30,
        "missed_large_positive": 0.25,
        "hard_negative_moderate": 0.25,
        "random_negative": 0.20,
    },
    "conservative_v1": {
        "medium_large_positive": 0.25,
        "missed_large_positive": 0.20,
        "hard_negative_moderate": 0.25,
        "random_negative": 0.30,
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build hard-mining pools and curriculum manifests from per-patch metrics."
    )

    parser.add_argument(
        "--run-dir",
        type=Path,
        required=True,
        help=(
            "Experiment run directory containing visual_predictions/<split>_best_thr*/"
            "per_patch_metrics_<split>.csv"
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory. Default: <run-dir>/hard_mining_manifest_224",
    )

    parser.add_argument(
        "--splits",
        nargs="+",
        default=DEFAULT_SPLITS,
        help="Splits to process. Default: train val test",
    )

    parser.add_argument(
        "--threshold-tag",
        type=str,
        default="best_thr0p450",
        help=(
            "Preferred visual_predictions folder suffix. Default: best_thr0p450. "
            "The script also searches automatically if this exact folder is absent."
        ),
    )

    parser.add_argument(
        "--target-size",
        type=int,
        default=None,
        help=(
            "Number of rows to sample for each curriculum manifest. "
            "Default: number of train patches."
        ),
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for curriculum sampling. Default: 42",
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite output directory if it exists.",
    )

    return parser.parse_args()


def prepare_output_dir(output_dir: Path, overwrite: bool) -> None:
    if output_dir.exists():
        if not overwrite:
            raise FileExistsError(
                f"Output directory already exists:\n"
                f"  {output_dir}\n\n"
                f"Use --overwrite to replace it."
            )
        shutil.rmtree(output_dir)

    (output_dir / "csv").mkdir(parents=True, exist_ok=True)
    (output_dir / "figures").mkdir(parents=True, exist_ok=True)


def find_metrics_csv(run_dir: Path, split: str, threshold_tag: str) -> Path:
    visual_root = run_dir / "visual_predictions"

    direct_candidates = [
        visual_root / f"{split}_{threshold_tag}" / f"per_patch_metrics_{split}.csv",
        visual_root / f"{split}_best_thr0p450" / f"per_patch_metrics_{split}.csv",
        visual_root / f"{split}_best" / f"per_patch_metrics_{split}.csv",
    ]

    for candidate in direct_candidates:
        if candidate.exists():
            return candidate

    glob_candidates = sorted(
        visual_root.glob(f"{split}_best_thr*/per_patch_metrics_{split}.csv")
    )

    if glob_candidates:
        return glob_candidates[0]

    raise FileNotFoundError(
        f"Could not find per_patch_metrics_{split}.csv under:\n"
        f"  {visual_root}\n\n"
        f"Expected something like:\n"
        f"  {visual_root}/{split}_best_thr0p450/per_patch_metrics_{split}.csv"
    )


def normalise_required_columns(df: pd.DataFrame, split: str) -> pd.DataFrame:
    """
    Make the script robust to small variations in column names.
    """

    df = df.copy()

    rename_candidates = {
        "gt_pos_pct": [
            "gt_pos_pct",
            "gt_favela_pct",
            "label_pos_pct",
            "mask_pos_pct",
            "gt_positive_pct",
        ],
        "pred_pos_pct": [
            "pred_pos_pct",
            "prediction_pos_pct",
            "pred_favela_pct",
            "pred_positive_pct",
        ],
        "iou_favela": [
            "iou_favela",
            "favela_iou",
            "iou",
            "patch_iou_favela",
        ],
        "dice_favela": [
            "dice_favela",
            "favela_dice",
            "dice",
            "patch_dice_favela",
        ],
        "precision_favela": [
            "precision_favela",
            "favela_precision",
            "precision",
        ],
        "recall_favela": [
            "recall_favela",
            "favela_recall",
            "recall",
        ],
        "fp_pct": [
            "fp_pct",
            "false_positive_pct",
        ],
        "fn_pct": [
            "fn_pct",
            "false_negative_pct",
        ],
    }

    for standard_name, possible_names in rename_candidates.items():
        if standard_name in df.columns:
            continue

        for candidate in possible_names:
            if candidate in df.columns:
                df = df.rename(columns={candidate: standard_name})
                break

    required = ["gt_pos_pct", "pred_pos_pct"]

    missing = [col for col in required if col not in df.columns]
    if missing:
        raise ValueError(
            f"Missing required columns in split={split}: {missing}\n\n"
            f"Available columns are:\n{list(df.columns)}"
        )

    if "split" not in df.columns:
        df["split"] = split
    else:
        df["split"] = df["split"].fillna(split)

    if "city" not in df.columns:
        df["city"] = "unknown_city"

    if "region" not in df.columns:
        df["region"] = "unknown_region"

    if "patch_id" not in df.columns:
        df["patch_id"] = [f"{split}_patch_{i:06d}" for i in range(len(df))]

    numeric_cols = [
        "gt_pos_pct",
        "pred_pos_pct",
        "iou_favela",
        "dice_favela",
        "precision_favela",
        "recall_favela",
        "fp_pct",
        "fn_pct",
    ]

    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    df["gt_pos_pct"] = df["gt_pos_pct"].fillna(0.0).clip(0.0, 100.0)
    df["pred_pos_pct"] = df["pred_pos_pct"].fillna(0.0).clip(0.0, 100.0)

    if "iou_favela" not in df.columns:
        df["iou_favela"] = np.nan

    if "dice_favela" not in df.columns:
        df["dice_favela"] = np.nan

    if "precision_favela" not in df.columns:
        df["precision_favela"] = np.nan

    if "recall_favela" not in df.columns:
        df["recall_favela"] = np.nan

    return df


def add_confusion_percentages(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add tp_pct, fp_pct, fn_pct, tn_pct.

    Since all patches have the same size, summing percentages across patches is
    equivalent to summing pixel counts up to a constant factor.

    Priority:
        1. Use fp_pct/fn_pct if already available.
        2. Infer TP/FP/FN from IoU, GT %, and predicted %.
        3. Fall back to a weak min(GT, pred) approximation.
    """

    df = df.copy()

    gt = df["gt_pos_pct"].fillna(0.0).clip(0.0, 100.0)
    pred = df["pred_pos_pct"].fillna(0.0).clip(0.0, 100.0)

    has_fp_fn = (
        "fp_pct" in df.columns
        and "fn_pct" in df.columns
        and not df["fp_pct"].isna().all()
        and not df["fn_pct"].isna().all()
    )

    if has_fp_fn:
        fp = df["fp_pct"].fillna(0.0).clip(0.0, 100.0)
        fn = df["fn_pct"].fillna(0.0).clip(0.0, 100.0)
        tp = (gt - fn).clip(0.0, 100.0)
    elif "iou_favela" in df.columns and not df["iou_favela"].isna().all():
        iou = df["iou_favela"].fillna(0.0).clip(0.0, 1.0)

        # IoU = TP / (GT + Pred - TP)
        # TP = IoU * (GT + Pred) / (1 + IoU)
        tp = (iou * (gt + pred) / (1.0 + iou)).fillna(0.0).clip(0.0, 100.0)
        fp = (pred - tp).clip(0.0, 100.0)
        fn = (gt - tp).clip(0.0, 100.0)
    else:
        tp = np.minimum(gt, pred)
        fp = (pred - tp).clip(0.0, 100.0)
        fn = (gt - tp).clip(0.0, 100.0)

    tn = (100.0 - tp - fp - fn).clip(0.0, 100.0)

    df["tp_pct"] = tp
    df["fp_pct"] = fp
    df["fn_pct"] = fn
    df["tn_pct"] = tn

    # Fill precision/recall if missing.
    precision_den = df["tp_pct"] + df["fp_pct"]
    recall_den = df["tp_pct"] + df["fn_pct"]

    inferred_precision = np.where(
        precision_den > 0,
        df["tp_pct"] / precision_den,
        0.0,
    )

    inferred_recall = np.where(
        recall_den > 0,
        df["tp_pct"] / recall_den,
        0.0,
    )

    df["precision_favela"] = df["precision_favela"].fillna(
        pd.Series(inferred_precision, index=df.index)
    )
    df["recall_favela"] = df["recall_favela"].fillna(
        pd.Series(inferred_recall, index=df.index)
    )

    # Fill Dice if missing.
    dice_den = 2.0 * df["tp_pct"] + df["fp_pct"] + df["fn_pct"]
    inferred_dice = np.where(
        dice_den > 0,
        2.0 * df["tp_pct"] / dice_den,
        0.0,
    )

    df["dice_favela"] = df["dice_favela"].fillna(
        pd.Series(inferred_dice, index=df.index)
    )

    # Fill IoU if missing.
    iou_den = df["tp_pct"] + df["fp_pct"] + df["fn_pct"]
    inferred_iou = np.where(
        iou_den > 0,
        df["tp_pct"] / iou_den,
        0.0,
    )

    df["iou_favela"] = df["iou_favela"].fillna(
        pd.Series(inferred_iou, index=df.index)
    )

    return df


def add_hard_mining_flags(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    gt = df["gt_pos_pct"]
    pred = df["pred_pos_pct"]
    diff = pred - gt
    iou = df["iou_favela"].fillna(0.0)
    recall = df["recall_favela"].fillna(0.0)

    df["pred_minus_gt_pct"] = diff

    df["pool_hard_negative_strict"] = (gt <= 1.0) & (pred >= 20.0)
    df["pool_hard_negative_moderate"] = (gt <= 5.0) & (pred >= 10.0)

    df["pool_missed_large_positive"] = (gt >= 10.0) & (recall < 0.40)
    df["pool_severe_missed_large_positive"] = (gt >= 20.0) & (diff <= -10.0)

    df["pool_good_large_positive"] = (gt >= 10.0) & (iou >= 0.50)
    df["pool_medium_large_positive"] = gt >= 5.0

    df["pool_random_negative"] = (gt <= 0.0) & (pred <= 1.0)

    # A compact multi-label string for quick inspection.
    pool_cols = [f"pool_{name}" for name in TRAIN_POOL_EXPORTS]

    def labels_for_row(row: pd.Series) -> str:
        labels = [name for name in TRAIN_POOL_EXPORTS if bool(row[f"pool_{name}"])]
        return ";".join(labels) if labels else "none"

    df["hard_mining_labels"] = df.apply(labels_for_row, axis=1)

    return df


def read_all_splits(
    run_dir: Path,
    splits: Sequence[str],
    threshold_tag: str,
) -> Tuple[pd.DataFrame, Dict[str, str]]:
    frames: List[pd.DataFrame] = []
    paths: Dict[str, str] = {}

    for split in splits:
        csv_path = find_metrics_csv(
            run_dir=run_dir,
            split=split,
            threshold_tag=threshold_tag,
        )
        paths[split] = str(csv_path)

        df = pd.read_csv(csv_path)
        df = normalise_required_columns(df, split=split)
        df = add_confusion_percentages(df)
        df = add_hard_mining_flags(df)

        frames.append(df)

    all_df = pd.concat(frames, ignore_index=True)
    return all_df, paths


def pool_column(pool_name: str) -> str:
    return f"pool_{pool_name}"


def subset_pool(df: pd.DataFrame, pool_name: str) -> pd.DataFrame:
    col = pool_column(pool_name)
    if col not in df.columns:
        raise KeyError(f"Pool column not found: {col}")
    return df[df[col]].copy()


def safe_mean(series: pd.Series) -> float:
    if len(series) == 0:
        return float("nan")
    return float(pd.to_numeric(series, errors="coerce").mean())


def build_pool_summary(
    df: pd.DataFrame,
    group_cols: Sequence[str],
    pool_names: Sequence[str],
) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    if group_cols:
        grouped = df.groupby(list(group_cols), dropna=False, observed=True)
        iterator = grouped
    else:
        iterator = [((), df)]

    for keys, group in iterator:
        if not isinstance(keys, tuple):
            keys = (keys,)

        for pool_name in pool_names:
            pool_df = subset_pool(group, pool_name)

            row: Dict[str, object] = {}

            for col, key in zip(group_cols, keys):
                row[col] = key

            row["pool"] = pool_name
            row["pool_description"] = POOL_DEFINITIONS[pool_name]["description"]
            row["n_patches"] = int(len(pool_df))
            row["group_total_patches"] = int(len(group))
            row["fraction_of_group"] = (
                float(len(pool_df) / len(group)) if len(group) > 0 else 0.0
            )

            if len(pool_df) > 0:
                row["mean_gt_pos_pct"] = safe_mean(pool_df["gt_pos_pct"])
                row["mean_pred_pos_pct"] = safe_mean(pool_df["pred_pos_pct"])
                row["mean_pred_minus_gt_pct"] = safe_mean(pool_df["pred_minus_gt_pct"])
                row["mean_iou_favela"] = safe_mean(pool_df["iou_favela"])
                row["mean_precision_favela"] = safe_mean(pool_df["precision_favela"])
                row["mean_recall_favela"] = safe_mean(pool_df["recall_favela"])
            else:
                row["mean_gt_pos_pct"] = np.nan
                row["mean_pred_pos_pct"] = np.nan
                row["mean_pred_minus_gt_pct"] = np.nan
                row["mean_iou_favela"] = np.nan
                row["mean_precision_favela"] = np.nan
                row["mean_recall_favela"] = np.nan

            rows.append(row)

    return pd.DataFrame(rows)


def save_train_pool_csvs(train_df: pd.DataFrame, csv_dir: Path) -> Dict[str, int]:
    counts: Dict[str, int] = {}

    for pool_name in TRAIN_POOL_EXPORTS:
        pool_df = subset_pool(train_df, pool_name)
        counts[pool_name] = int(len(pool_df))

        out_path = csv_dir / f"train_{pool_name}.csv"
        pool_df.to_csv(out_path, index=False)

    return counts


def allocate_counts(target_size: int, recipe: Dict[str, float]) -> Dict[str, int]:
    """
    Convert fractions into integer sample counts that sum exactly to target_size.
    """

    raw = {pool: frac * target_size for pool, frac in recipe.items()}
    base = {pool: int(np.floor(value)) for pool, value in raw.items()}

    remainder = target_size - sum(base.values())

    fractional_parts = sorted(
        ((pool, raw[pool] - base[pool]) for pool in recipe),
        key=lambda x: x[1],
        reverse=True,
    )

    for i in range(remainder):
        pool = fractional_parts[i % len(fractional_parts)][0]
        base[pool] += 1

    return base


def sample_pool_rows(
    train_df: pd.DataFrame,
    pool_name: str,
    n_samples: int,
    rng: np.random.Generator,
) -> pd.DataFrame:
    pool_df = subset_pool(train_df, pool_name)

    if n_samples <= 0:
        return pd.DataFrame(columns=train_df.columns)

    if len(pool_df) == 0:
        print(
            f"WARNING: pool '{pool_name}' is empty. "
            f"Cannot sample {n_samples} rows from it."
        )
        return pd.DataFrame(columns=train_df.columns)

    replace = len(pool_df) < n_samples

    sampled_indices = rng.choice(
        pool_df.index.to_numpy(),
        size=n_samples,
        replace=replace,
    )

    sampled = train_df.loc[sampled_indices].copy()
    sampled["sample_pool"] = pool_name
    sampled["sampled_with_replacement"] = bool(replace)

    return sampled


def build_curriculum_manifest(
    train_df: pd.DataFrame,
    recipe_name: str,
    recipe: Dict[str, float],
    target_size: int,
    seed: int,
) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    sample_counts = allocate_counts(target_size=target_size, recipe=recipe)

    sampled_parts: List[pd.DataFrame] = []

    for pool_name, n_samples in sample_counts.items():
        sampled = sample_pool_rows(
            train_df=train_df,
            pool_name=pool_name,
            n_samples=n_samples,
            rng=rng,
        )
        sampled_parts.append(sampled)

    if sampled_parts:
        manifest = pd.concat(sampled_parts, ignore_index=True)
    else:
        manifest = pd.DataFrame(columns=train_df.columns)

    if len(manifest) > 0:
        manifest = manifest.sample(
            frac=1.0,
            random_state=seed,
        ).reset_index(drop=True)

        manifest["curriculum_recipe"] = recipe_name
        manifest["curriculum_target_size"] = target_size
        manifest["curriculum_row_id"] = [
            f"{recipe_name}_{i:06d}" for i in range(len(manifest))
        ]

        # Suggested per-sample weight. This is optional for future training code.
        # Rows sampled from small pools may appear multiple times instead.
        manifest["sample_weight"] = 1.0

    return manifest


def deduplicate_manifest(manifest: pd.DataFrame) -> pd.DataFrame:
    if len(manifest) == 0:
        return manifest.copy()

    if "patch_id" in manifest.columns:
        key_cols = ["split", "city", "patch_id"]
    else:
        key_cols = ["split", "city"]

    existing_key_cols = [col for col in key_cols if col in manifest.columns]

    if not existing_key_cols:
        return manifest.drop_duplicates().copy()

    dedup = manifest.drop_duplicates(subset=existing_key_cols).copy()
    dedup = dedup.reset_index(drop=True)
    dedup["unique_manifest_row_id"] = [f"unique_{i:06d}" for i in range(len(dedup))]

    return dedup


def save_curriculum_manifests(
    train_df: pd.DataFrame,
    csv_dir: Path,
    target_size: int,
    seed: int,
) -> Dict[str, Dict[str, int]]:
    summary: Dict[str, Dict[str, int]] = {}

    for recipe_name, recipe in CURRICULUM_RECIPES.items():
        manifest = build_curriculum_manifest(
            train_df=train_df,
            recipe_name=recipe_name,
            recipe=recipe,
            target_size=target_size,
            seed=seed,
        )

        dedup = deduplicate_manifest(manifest)

        manifest_path = csv_dir / f"train_curriculum_manifest_{recipe_name}.csv"
        dedup_path = csv_dir / f"train_curriculum_manifest_{recipe_name}_unique.csv"

        manifest.to_csv(manifest_path, index=False)
        dedup.to_csv(dedup_path, index=False)

        summary[recipe_name] = {
            "target_size": int(target_size),
            "n_rows_sampled_manifest": int(len(manifest)),
            "n_rows_unique_manifest": int(len(dedup)),
        }

        for pool_name in recipe:
            summary[recipe_name][f"requested_{pool_name}"] = int(
                allocate_counts(target_size, recipe)[pool_name]
            )
            summary[recipe_name][f"available_{pool_name}"] = int(
                subset_pool(train_df, pool_name).shape[0]
            )

    return summary


def bar_plot(
    labels: Sequence[str],
    values: Sequence[float],
    title: str,
    ylabel: str,
    out_path: Path,
    rotation: int = 35,
) -> None:
    x = np.arange(len(labels))

    fig_width = max(9, len(labels) * 0.9)
    fig, ax = plt.subplots(figsize=(fig_width, 5.5))

    ax.bar(x, values)
    ax.set_title(title)
    ax.set_ylabel(ylabel)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=rotation, ha="right")
    ax.grid(axis="y", alpha=0.3)

    for i, value in enumerate(values):
        ax.text(i, value, str(int(value)), ha="center", va="bottom", fontsize=8)

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def grouped_bar_plot(
    df: pd.DataFrame,
    x_col: str,
    y_col: str,
    group_col: str,
    title: str,
    ylabel: str,
    out_path: Path,
    rotation: int = 35,
) -> None:
    plot_df = df.copy()

    pivot = plot_df.pivot_table(
        index=x_col,
        columns=group_col,
        values=y_col,
        aggfunc="sum",
        observed=False,
    ).fillna(0)

    labels = list(pivot.index.astype(str))
    groups = list(pivot.columns.astype(str))

    x = np.arange(len(labels))
    n_groups = max(len(groups), 1)
    width = 0.8 / n_groups

    fig_width = max(10, len(labels) * 0.9)
    fig, ax = plt.subplots(figsize=(fig_width, 5.8))

    for i, group in enumerate(groups):
        values = pivot[group].values
        offset = (i - (n_groups - 1) / 2.0) * width
        ax.bar(x + offset, values, width, label=group)

    ax.set_title(title)
    ax.set_ylabel(ylabel)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=rotation, ha="right")
    ax.grid(axis="y", alpha=0.3)
    ax.legend(title=group_col)

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def stacked_city_pool_plot(
    train_df: pd.DataFrame,
    out_path: Path,
    pool_names: Sequence[str],
) -> None:
    rows: List[Dict[str, object]] = []

    for city, city_df in train_df.groupby("city", observed=True):
        row: Dict[str, object] = {"city": city}
        for pool_name in pool_names:
            row[pool_name] = int(subset_pool(city_df, pool_name).shape[0])
        rows.append(row)

    if not rows:
        return

    city_counts = pd.DataFrame(rows)
    city_counts["total_selected"] = city_counts[list(pool_names)].sum(axis=1)
    city_counts = city_counts.sort_values("total_selected", ascending=False)

    x = np.arange(len(city_counts))
    fig_width = max(10, len(city_counts) * 0.75)

    fig, ax = plt.subplots(figsize=(fig_width, 6.2))

    bottom = np.zeros(len(city_counts))

    for pool_name in pool_names:
        values = city_counts[pool_name].values
        ax.bar(x, values, bottom=bottom, label=pool_name)
        bottom += values

    ax.set_title("Train hard-mining pool counts by city")
    ax.set_ylabel("Number of pool memberships")
    ax.set_xticks(x)
    ax.set_xticklabels(city_counts["city"].astype(str), rotation=45, ha="right")
    ax.grid(axis="y", alpha=0.3)
    ax.legend(loc="upper right", bbox_to_anchor=(1.32, 1.0))

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def save_figures(
    all_df: pd.DataFrame,
    train_df: pd.DataFrame,
    pool_summary_by_split: pd.DataFrame,
    curriculum_summary: Dict[str, Dict[str, int]],
    figures_dir: Path,
) -> None:
    train_counts = {
        pool_name: int(subset_pool(train_df, pool_name).shape[0])
        for pool_name in TRAIN_POOL_EXPORTS
    }

    bar_plot(
        labels=list(train_counts.keys()),
        values=list(train_counts.values()),
        title="Train hard-mining pool counts",
        ylabel="Number of train patches",
        out_path=figures_dir / "train_pool_counts.png",
    )

    grouped_bar_plot(
        df=pool_summary_by_split,
        x_col="pool",
        y_col="n_patches",
        group_col="split",
        title="Diagnostic pool counts by split",
        ylabel="Number of patches",
        out_path=figures_dir / "diagnostic_pool_counts_by_split.png",
    )

    stacked_city_pool_plot(
        train_df=train_df,
        out_path=figures_dir / "train_pool_counts_by_city.png",
        pool_names=[
            "medium_large_positive",
            "missed_large_positive",
            "hard_negative_moderate",
            "random_negative",
        ],
    )

    # Curriculum composition figure.
    rows: List[Dict[str, object]] = []
    for recipe_name, summary in curriculum_summary.items():
        for key, value in summary.items():
            if key.startswith("requested_"):
                pool = key.replace("requested_", "")
                rows.append(
                    {
                        "recipe": recipe_name,
                        "pool": pool,
                        "n_requested": int(value),
                    }
                )

    if rows:
        recipe_df = pd.DataFrame(rows)
        grouped_bar_plot(
            df=recipe_df,
            x_col="pool",
            y_col="n_requested",
            group_col="recipe",
            title="Curriculum manifest requested composition",
            ylabel="Number of sampled rows",
            out_path=figures_dir / "curriculum_manifest_composition.png",
        )


def create_report(
    output_dir: Path,
    metrics_paths: Dict[str, str],
    train_counts: Dict[str, int],
    pool_summary_by_split: pd.DataFrame,
    pool_summary_by_split_city: pd.DataFrame,
    curriculum_summary: Dict[str, Dict[str, int]],
) -> None:
    report_path = output_dir / "hard_mining_report.md"

    lines: List[str] = []

    lines.append("# Hard-Mining Manifest Report")
    lines.append("")
    lines.append("## Objective")
    lines.append("")
    lines.append(
        "This report summarizes hard-mining pools built from the current reBEN/UPerNet "
        "prediction diagnostics. Training manifests are built from the train split only "
        "to avoid validation/test leakage."
    )

    lines.append("")
    lines.append("## Input metric files")
    lines.append("")

    for split, path in metrics_paths.items():
        lines.append(f"- **{split}**: `{path}`")

    lines.append("")
    lines.append("## Pool definitions")
    lines.append("")
    lines.append("| Pool | Definition |")
    lines.append("|:--|:--|")

    for pool_name, info in POOL_DEFINITIONS.items():
        lines.append(f"| `{pool_name}` | {info['description']} |")

    lines.append("")
    lines.append("## Train pool counts")
    lines.append("")
    lines.append("| Pool | Count |")
    lines.append("|:--|--:|")

    for pool_name, count in train_counts.items():
        lines.append(f"| `{pool_name}` | {count} |")

    lines.append("")
    lines.append("## Diagnostic pool counts by split")
    lines.append("")

    compact_split = pool_summary_by_split[
        [
            "split",
            "pool",
            "n_patches",
            "fraction_of_group",
            "mean_gt_pos_pct",
            "mean_pred_pos_pct",
            "mean_pred_minus_gt_pct",
            "mean_iou_favela",
            "mean_precision_favela",
            "mean_recall_favela",
        ]
    ].copy()

    numeric_cols = [
        "fraction_of_group",
        "mean_gt_pos_pct",
        "mean_pred_pos_pct",
        "mean_pred_minus_gt_pct",
        "mean_iou_favela",
        "mean_precision_favela",
        "mean_recall_favela",
    ]

    for col in numeric_cols:
        compact_split[col] = compact_split[col].map(
            lambda x: "" if pd.isna(x) else f"{float(x):.4f}"
        )

    lines.append(compact_split.to_markdown(index=False))

    lines.append("")
    lines.append("## Curriculum manifests")
    lines.append("")
    lines.append(
        "The sampled curriculum manifests may contain duplicated patches because they "
        "are designed as oversampling manifests. Unique deduplicated versions are also exported."
    )
    lines.append("")

    lines.append("| Recipe | Sampled rows | Unique rows |")
    lines.append("|:--|--:|--:|")

    for recipe_name, summary in curriculum_summary.items():
        lines.append(
            f"| `{recipe_name}` | {summary['n_rows_sampled_manifest']} | "
            f"{summary['n_rows_unique_manifest']} |"
        )

    lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    lines.append(
        "- Hard negatives teach the model that dense built-up texture is not always favela."
    )
    lines.append(
        "- Missed large positives teach the model to recover full favela extent rather than only predicting conservative cores."
    )
    lines.append(
        "- Good large positives provide stable positive supervision."
    )
    lines.append(
        "- Random negatives prevent the next model from overfitting only to hard examples."
    )
    lines.append(
        "- The next training stage should use train-only hard-mining pools, while validation/test pools should remain diagnostic only."
    )

    lines.append("")
    lines.append("## Important output files")
    lines.append("")
    lines.append("- `csv/all_splits_hard_mining_enriched.csv`")
    lines.append("- `csv/train_hard_negative_strict.csv`")
    lines.append("- `csv/train_hard_negative_moderate.csv`")
    lines.append("- `csv/train_missed_large_positive.csv`")
    lines.append("- `csv/train_severe_missed_large_positive.csv`")
    lines.append("- `csv/train_good_large_positive.csv`")
    lines.append("- `csv/train_medium_large_positive.csv`")
    lines.append("- `csv/train_random_negative.csv`")
    lines.append("- `csv/train_curriculum_manifest_balanced_v1.csv`")
    lines.append("- `csv/train_curriculum_manifest_balanced_v1_unique.csv`")
    lines.append("- `csv/train_curriculum_manifest_conservative_v1.csv`")
    lines.append("- `csv/train_curriculum_manifest_conservative_v1_unique.csv`")

    report_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()

    run_dir: Path = args.run_dir
    output_dir: Path = (
        args.output_dir
        if args.output_dir is not None
        else run_dir / "hard_mining_manifest_224"
    )

    prepare_output_dir(output_dir=output_dir, overwrite=args.overwrite)

    all_df, metrics_paths = read_all_splits(
        run_dir=run_dir,
        splits=args.splits,
        threshold_tag=args.threshold_tag,
    )

    csv_dir = output_dir / "csv"
    figures_dir = output_dir / "figures"

    all_df.to_csv(
        csv_dir / "all_splits_hard_mining_enriched.csv",
        index=False,
    )

    train_df = all_df[all_df["split"] == "train"].copy()

    if len(train_df) == 0:
        raise ValueError(
            "No train rows found. Cannot build training hard-mining manifests."
        )

    train_counts = save_train_pool_csvs(
        train_df=train_df,
        csv_dir=csv_dir,
    )

    pool_summary_by_split = build_pool_summary(
        df=all_df,
        group_cols=["split"],
        pool_names=TRAIN_POOL_EXPORTS,
    )

    pool_summary_by_split.to_csv(
        csv_dir / "diagnostic_pool_summary_by_split.csv",
        index=False,
    )

    pool_summary_by_split_city = build_pool_summary(
        df=all_df,
        group_cols=["split", "region", "city"],
        pool_names=TRAIN_POOL_EXPORTS,
    )

    pool_summary_by_split_city.to_csv(
        csv_dir / "diagnostic_pool_summary_by_split_city.csv",
        index=False,
    )

    target_size = args.target_size if args.target_size is not None else len(train_df)

    curriculum_summary = save_curriculum_manifests(
        train_df=train_df,
        csv_dir=csv_dir,
        target_size=target_size,
        seed=args.seed,
    )

    save_figures(
        all_df=all_df,
        train_df=train_df,
        pool_summary_by_split=pool_summary_by_split,
        curriculum_summary=curriculum_summary,
        figures_dir=figures_dir,
    )

    metadata = {
        "run_dir": str(run_dir),
        "output_dir": str(output_dir),
        "splits": args.splits,
        "metrics_paths": metrics_paths,
        "pool_definitions": POOL_DEFINITIONS,
        "curriculum_recipes": CURRICULUM_RECIPES,
        "target_size": int(target_size),
        "seed": int(args.seed),
        "important_note": (
            "Training manifests are built from train split only. "
            "Validation/test hard pools are diagnostic only and must not be used for training."
        ),
    }

    with (output_dir / "metadata.json").open("w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    create_report(
        output_dir=output_dir,
        metrics_paths=metrics_paths,
        train_counts=train_counts,
        pool_summary_by_split=pool_summary_by_split,
        pool_summary_by_split_city=pool_summary_by_split_city,
        curriculum_summary=curriculum_summary,
    )

    print("\nDone. Hard-mining manifests written to:")
    print(f"  {output_dir}")

    print("\nMain report:")
    print(f"  {output_dir / 'hard_mining_report.md'}")

    print("\nTrain pool counts:")
    for pool_name, count in train_counts.items():
        print(f"  {pool_name:32s}: {count}")

    print("\nCurriculum manifests:")
    for recipe_name, summary in curriculum_summary.items():
        print(
            f"  {recipe_name:16s}: "
            f"sampled={summary['n_rows_sampled_manifest']}, "
            f"unique={summary['n_rows_unique_manifest']}"
        )

    print("\nImportant note:")
    print("  Use only train_* CSVs for training. Val/test pools are diagnostic only.")


if __name__ == "__main__":
    main()