# src/big_earth_net/make_simplified_diagnostic_plots_224.py

"""
Create simplified diagnostic plots for the reBEN ResNet18 + UPerNet favela
segmentation baseline.

This script reads per-patch metric CSV files generated by:
    src/big_earth_net/visualize_reben_predictions_224.py

It creates simplified train/val/test summaries by:
    - label-density bin
    - prediction-density bin
    - simplified error mode
    - city
    - region

The purpose is to make the diagnostic story easier to communicate:
    1. The model works better on large/continuous favela patches.
    2. The dataset is dominated by empty/tiny/low-density patches.
    3. The model systematically overpredicts favela area.
    4. Some cities/regions look better partly because they contain denser labels.
    5. Error modes can be collapsed into a few interpretable groups.

Author: Mahmoud Abo Shukr
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


LABEL_BIN_ORDER = [
    "Empty (0%)",
    "Tiny (0-1%)",
    "Small (1-5%)",
    "Medium (5-20%)",
    "Large (>20%)",
]

PRED_BIN_ORDER = [
    "No prediction (0%)",
    "Tiny prediction (0-1%)",
    "Small prediction (1-5%)",
    "Medium prediction (5-20%)",
    "Large prediction (>20%)",
]

ERROR_GROUP_ORDER = [
    "Correct / acceptable",
    "Tiny-object problem",
    "Overprediction problem",
    "Underprediction problem",
    "Ambiguous / weak positive",
]

DEFAULT_SPLITS = ["train", "val", "test"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create simplified diagnostic plots from reBEN per-patch metrics."
    )

    parser.add_argument(
        "--run-dir",
        type=Path,
        required=True,
        help=(
            "Experiment run directory containing visual_predictions/<split>_best_thr*/"
            "per_patch_metrics_<split>.csv"
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Output directory. Default: <run-dir>/simplified_diagnostics_224"
        ),
    )

    parser.add_argument(
        "--splits",
        nargs="+",
        default=DEFAULT_SPLITS,
        help="Splits to process. Default: train val test",
    )

    parser.add_argument(
        "--patch-size",
        type=int,
        default=224,
        help="Patch size in pixels. Default: 224",
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite output directory if it exists.",
    )

    return parser.parse_args()


def find_metrics_csv(run_dir: Path, split: str) -> Path:
    """
    Find per_patch_metrics_<split>.csv inside the run directory.

    Expected examples:
        visual_predictions/train_best_thr0p450/per_patch_metrics_train.csv
        visual_predictions/val_best_thr0p450/per_patch_metrics_val.csv
        visual_predictions/test_best_thr0p450/per_patch_metrics_test.csv
    """

    visual_root = run_dir / "visual_predictions"

    direct_candidates = [
        visual_root / f"{split}_best_thr0p450" / f"per_patch_metrics_{split}.csv",
        visual_root / f"{split}_best" / f"per_patch_metrics_{split}.csv",
    ]

    for candidate in direct_candidates:
        if candidate.exists():
            return candidate

    glob_candidates = sorted(
        visual_root.glob(f"{split}_best_thr*/per_patch_metrics_{split}.csv")
    )

    if glob_candidates:
        return glob_candidates[0]

    raise FileNotFoundError(
        f"Could not find per_patch_metrics_{split}.csv under:\n"
        f"  {visual_root}\n"
        f"Expected something like:\n"
        f"  {visual_root}/{split}_best_thr0p450/per_patch_metrics_{split}.csv"
    )


def prepare_output_dir(output_dir: Path, overwrite: bool) -> None:
    if output_dir.exists():
        if not overwrite:
            raise FileExistsError(
                f"Output directory already exists:\n"
                f"  {output_dir}\n"
                f"Use --overwrite to replace it."
            )
        shutil.rmtree(output_dir)

    (output_dir / "figures").mkdir(parents=True, exist_ok=True)
    (output_dir / "csv").mkdir(parents=True, exist_ok=True)


def normalise_required_columns(df: pd.DataFrame, split: str) -> pd.DataFrame:
    """
    Make the script robust to small variations in column naming.
    """

    df = df.copy()

    rename_candidates = {
        "gt_pos_pct": ["gt_pos_pct", "gt_favela_pct", "label_pos_pct", "mask_pos_pct"],
        "pred_pos_pct": ["pred_pos_pct", "prediction_pos_pct", "pred_favela_pct"],
        "iou_favela": ["iou_favela", "favela_iou", "iou"],
        "dice_favela": ["dice_favela", "favela_dice", "dice"],
        "precision_favela": ["precision_favela", "favela_precision", "precision"],
        "recall_favela": ["recall_favela", "favela_recall", "recall"],
        "fp_pct": ["fp_pct", "false_positive_pct"],
        "fn_pct": ["fn_pct", "false_negative_pct"],
    }

    for standard_name, possible_names in rename_candidates.items():
        if standard_name in df.columns:
            continue

        for candidate in possible_names:
            if candidate in df.columns:
                df = df.rename(columns={candidate: standard_name})
                break

    required = ["gt_pos_pct", "pred_pos_pct"]
    missing = [col for col in required if col not in df.columns]
    if missing:
        raise ValueError(
            f"Missing required columns in split={split}: {missing}\n"
            f"Available columns are:\n{list(df.columns)}"
        )

    if "split" not in df.columns:
        df["split"] = split
    else:
        df["split"] = df["split"].fillna(split)

    if "city" not in df.columns:
        df["city"] = "unknown_city"

    if "region" not in df.columns:
        df["region"] = "unknown_region"

    if "patch_id" not in df.columns:
        df["patch_id"] = [f"{split}_patch_{i:06d}" for i in range(len(df))]

    numeric_cols = [
        "gt_pos_pct",
        "pred_pos_pct",
        "iou_favela",
        "dice_favela",
        "precision_favela",
        "recall_favela",
        "fp_pct",
        "fn_pct",
    ]

    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    df["gt_pos_pct"] = df["gt_pos_pct"].fillna(0.0).clip(0.0, 100.0)
    df["pred_pos_pct"] = df["pred_pos_pct"].fillna(0.0).clip(0.0, 100.0)

    return df


def add_confusion_percentages(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add tp_pct, fp_pct, fn_pct, tn_pct.

    If fp_pct and fn_pct already exist, use them.
    Otherwise infer TP from IoU, GT percentage, and prediction percentage.

    Since all patches have the same size, summing percentages across patches is
    equivalent to summing pixel counts up to a constant factor.
    """

    df = df.copy()

    gt = df["gt_pos_pct"].fillna(0.0).clip(0.0, 100.0)
    pred = df["pred_pos_pct"].fillna(0.0).clip(0.0, 100.0)

    if "fp_pct" in df.columns and "fn_pct" in df.columns:
        fp = df["fp_pct"].fillna(0.0).clip(0.0, 100.0)
        fn = df["fn_pct"].fillna(0.0).clip(0.0, 100.0)
        tp = (gt - fn).clip(0.0, 100.0)
    elif "iou_favela" in df.columns:
        iou = df["iou_favela"].fillna(0.0).clip(0.0, 1.0)

        # IoU = TP / (GT + Pred - TP)
        # TP = IoU * (GT + Pred) / (1 + IoU)
        tp = (iou * (gt + pred) / (1.0 + iou)).fillna(0.0).clip(0.0, 100.0)
        fp = (pred - tp).clip(0.0, 100.0)
        fn = (gt - tp).clip(0.0, 100.0)
    else:
        # Last-resort approximation if IoU and FP/FN are unavailable.
        # This is not ideal, but keeps the script usable.
        tp = np.minimum(gt, pred)
        fp = (pred - tp).clip(0.0, 100.0)
        fn = (gt - tp).clip(0.0, 100.0)

    tn = (100.0 - tp - fp - fn).clip(0.0, 100.0)

    df["tp_pct"] = tp
    df["fp_pct"] = fp
    df["fn_pct"] = fn
    df["tn_pct"] = tn

    return df


def assign_label_density_bin(gt_pos_pct: float) -> str:
    if gt_pos_pct <= 0:
        return "Empty (0%)"
    if gt_pos_pct <= 1:
        return "Tiny (0-1%)"
    if gt_pos_pct <= 5:
        return "Small (1-5%)"
    if gt_pos_pct <= 20:
        return "Medium (5-20%)"
    return "Large (>20%)"


def assign_prediction_density_bin(pred_pos_pct: float) -> str:
    if pred_pos_pct <= 0:
        return "No prediction (0%)"
    if pred_pos_pct <= 1:
        return "Tiny prediction (0-1%)"
    if pred_pos_pct <= 5:
        return "Small prediction (1-5%)"
    if pred_pos_pct <= 20:
        return "Medium prediction (5-20%)"
    return "Large prediction (>20%)"


def map_existing_error_mode(mode: str) -> str:
    mode = str(mode)

    correct = {
        "good_empty_or_near_empty",
        "good_positive",
    }

    tiny = {
        "tiny_fragment_missed",
        "tiny_positive_other",
    }

    over = {
        "severe_overprediction",
        "hard_false_positive",
    }

    under = {
        "hard_false_negative",
        "severe_underprediction",
    }

    ambiguous = {
        "mixed_or_average",
        "low_iou_positive_other",
    }

    if mode in correct:
        return "Correct / acceptable"
    if mode in tiny:
        return "Tiny-object problem"
    if mode in over:
        return "Overprediction problem"
    if mode in under:
        return "Underprediction problem"
    if mode in ambiguous:
        return "Ambiguous / weak positive"

    return "Ambiguous / weak positive"


def infer_error_group(row: pd.Series) -> str:
    """
    Infer a simplified error group when dominant_error_mode is not available.
    """

    gt = float(row.get("gt_pos_pct", 0.0))
    pred = float(row.get("pred_pos_pct", 0.0))
    iou = float(row.get("iou_favela", 0.0))
    recall = float(row.get("recall_favela", 0.0))

    if gt == 0 and pred <= 1:
        return "Correct / acceptable"

    if gt > 0 and iou >= 0.5:
        return "Correct / acceptable"

    if 0 < gt <= 1:
        return "Tiny-object problem"

    if (pred - gt) >= 10 or (gt <= 5 and pred >= 10):
        return "Overprediction problem"

    if (gt - pred) >= 5 or (gt >= 5 and recall < 0.25):
        return "Underprediction problem"

    return "Ambiguous / weak positive"


def add_simplified_bins(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df["simple_label_density_bin"] = df["gt_pos_pct"].apply(assign_label_density_bin)
    df["simple_prediction_density_bin"] = df["pred_pos_pct"].apply(
        assign_prediction_density_bin
    )

    df["simple_label_density_bin"] = pd.Categorical(
        df["simple_label_density_bin"],
        categories=LABEL_BIN_ORDER,
        ordered=True,
    )

    df["simple_prediction_density_bin"] = pd.Categorical(
        df["simple_prediction_density_bin"],
        categories=PRED_BIN_ORDER,
        ordered=True,
    )

    if "dominant_error_mode" in df.columns:
        df["simple_error_group"] = df["dominant_error_mode"].apply(
            map_existing_error_mode
        )
    else:
        df["simple_error_group"] = df.apply(infer_error_group, axis=1)

    df["simple_error_group"] = pd.Categorical(
        df["simple_error_group"],
        categories=ERROR_GROUP_ORDER,
        ordered=True,
    )

    return df


def safe_div(num: float, den: float) -> float:
    if den == 0:
        return 0.0
    return float(num / den)


def aggregate_metrics(
    df: pd.DataFrame,
    group_cols: Sequence[str],
) -> pd.DataFrame:
    """
    Aggregate global segmentation metrics using summed TP/FP/FN/TN percentages.
    """

    rows: List[Dict[str, object]] = []

    if group_cols:
        grouped = df.groupby(list(group_cols), dropna=False, observed=True)
        iterator = grouped
    else:
        iterator = [((), df)]

    for keys, group in iterator:
        if not isinstance(keys, tuple):
            keys = (keys,)

        row: Dict[str, object] = {}

        for col, key in zip(group_cols, keys):
            row[col] = key

        tp = float(group["tp_pct"].sum())
        fp = float(group["fp_pct"].sum())
        fn = float(group["fn_pct"].sum())
        tn = float(group["tn_pct"].sum())

        n = int(len(group))

        row["n_patches"] = n
        row["global_iou_favela"] = safe_div(tp, tp + fp + fn)
        row["global_dice_favela"] = safe_div(2 * tp, 2 * tp + fp + fn)
        row["global_precision_favela"] = safe_div(tp, tp + fp)
        row["global_recall_favela"] = safe_div(tp, tp + fn)
        row["global_iou_no_favela"] = safe_div(tn, tn + fp + fn)
        row["global_accuracy"] = safe_div(tp + tn, tp + fp + fn + tn)

        row["mean_gt_pos_pct"] = float(group["gt_pos_pct"].mean())
        row["mean_pred_pos_pct"] = float(group["pred_pos_pct"].mean())
        row["mean_pred_minus_gt_pct"] = (
            row["mean_pred_pos_pct"] - row["mean_gt_pos_pct"]
        )

        if "iou_favela" in group.columns:
            row["patch_mean_iou_favela"] = float(group["iou_favela"].mean())
            row["patch_median_iou_favela"] = float(group["iou_favela"].median())

        if "dice_favela" in group.columns:
            row["patch_mean_dice_favela"] = float(group["dice_favela"].mean())

        rows.append(row)

    out = pd.DataFrame(rows)

    return out


def grouped_bar_plot(
    df: pd.DataFrame,
    x_col: str,
    y_col: str,
    group_col: str,
    x_order: Sequence[str],
    title: str,
    ylabel: str,
    out_path: Path,
    rotation: int = 30,
) -> None:
    plot_df = df.copy()
    plot_df[x_col] = plot_df[x_col].astype(str)

    pivot = plot_df.pivot_table(
        index=x_col,
        columns=group_col,
        values=y_col,
        aggfunc="first",
        observed=False,
    )

    pivot = pivot.reindex(list(x_order))

    groups = list(pivot.columns)
    x = np.arange(len(pivot.index))
    n_groups = max(len(groups), 1)
    width = 0.8 / n_groups

    fig_width = max(9, len(x_order) * 1.4)
    fig, ax = plt.subplots(figsize=(fig_width, 5.5))

    for i, group in enumerate(groups):
        values = pivot[group].fillna(0.0).values
        offset = (i - (n_groups - 1) / 2) * width
        ax.bar(x + offset, values, width, label=str(group))

    ax.set_title(title)
    ax.set_ylabel(ylabel)
    ax.set_xticks(x)
    ax.set_xticklabels(pivot.index, rotation=rotation, ha="right")
    ax.legend(title=group_col)
    ax.grid(axis="y", alpha=0.3)

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def simple_bar_plot(
    df: pd.DataFrame,
    x_col: str,
    y_col: str,
    title: str,
    ylabel: str,
    out_path: Path,
    rotation: int = 30,
    annotate_col: Optional[str] = None,
) -> None:
    plot_df = df.copy()
    x = np.arange(len(plot_df))

    fig_width = max(9, len(plot_df) * 0.8)
    fig, ax = plt.subplots(figsize=(fig_width, 5.5))

    values = plot_df[y_col].fillna(0.0).values
    ax.bar(x, values)

    ax.set_title(title)
    ax.set_ylabel(ylabel)
    ax.set_xticks(x)
    ax.set_xticklabels(plot_df[x_col].astype(str), rotation=rotation, ha="right")
    ax.grid(axis="y", alpha=0.3)

    if annotate_col is not None and annotate_col in plot_df.columns:
        for i, (_, row) in enumerate(plot_df.iterrows()):
            annotation = row[annotate_col]
            ax.text(
                i,
                values[i],
                f"{annotation:.2f}",
                ha="center",
                va="bottom",
                fontsize=8,
                rotation=0,
            )

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def stacked_error_by_city_plot(
    error_city_df: pd.DataFrame,
    split: str,
    out_path: Path,
) -> None:
    split_df = error_city_df[error_city_df["split"] == split].copy()

    if split_df.empty:
        return

    pivot = split_df.pivot_table(
        index="city",
        columns="simple_error_group",
        values="fraction",
        aggfunc="sum",
        observed=False,
    )

    pivot = pivot.reindex(columns=ERROR_GROUP_ORDER).fillna(0.0)

    # Sort by the fraction of correct cases, then by city name.
    if "Correct / acceptable" in pivot.columns:
        pivot = pivot.sort_values(
            by="Correct / acceptable",
            ascending=False,
        )
    else:
        pivot = pivot.sort_index()

    x = np.arange(len(pivot.index))
    fig_width = max(10, len(pivot.index) * 0.7)
    fig, ax = plt.subplots(figsize=(fig_width, 6.0))

    bottom = np.zeros(len(pivot.index))

    for group in ERROR_GROUP_ORDER:
        values = pivot[group].values if group in pivot.columns else np.zeros(len(x))
        ax.bar(x, values, bottom=bottom, label=group)
        bottom += values

    ax.set_title(f"Simplified error-mode fractions by city ({split})")
    ax.set_ylabel("Fraction of patches")
    ax.set_xticks(x)
    ax.set_xticklabels(pivot.index.astype(str), rotation=45, ha="right")
    ax.set_ylim(0, 1)
    ax.legend(loc="upper right", bbox_to_anchor=(1.25, 1.0))
    ax.grid(axis="y", alpha=0.3)

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def read_all_splits(run_dir: Path, splits: Sequence[str]) -> Tuple[pd.DataFrame, Dict[str, str]]:
    frames: List[pd.DataFrame] = []
    metrics_paths: Dict[str, str] = {}

    for split in splits:
        metrics_csv = find_metrics_csv(run_dir, split)
        metrics_paths[split] = str(metrics_csv)

        df = pd.read_csv(metrics_csv)
        df = normalise_required_columns(df, split=split)
        df = add_confusion_percentages(df)
        df = add_simplified_bins(df)

        frames.append(df)

    all_df = pd.concat(frames, ignore_index=True)
    return all_df, metrics_paths


def create_report(
    output_dir: Path,
    metrics_paths: Dict[str, str],
    summary_by_split: pd.DataFrame,
    label_density_metrics: pd.DataFrame,
    region_metrics: pd.DataFrame,
) -> None:
    report_path = output_dir / "simplified_diagnostic_report.md"

    lines: List[str] = []

    lines.append("# Simplified reBEN Diagnostic Report")
    lines.append("")
    lines.append("## Input metric files")
    lines.append("")

    for split, path in metrics_paths.items():
        lines.append(f"- **{split}**: `{path}`")

    lines.append("")
    lines.append("## Overall split summary")
    lines.append("")
    lines.append(summary_by_split.to_markdown(index=False))
    lines.append("")

    lines.append("## Main interpretation")
    lines.append("")
    lines.append(
        "- The baseline is not completely broken: it learns a meaningful favela signal, especially on larger favela patches."
    )
    lines.append(
        "- The train/validation/test gap indicates overfitting and/or city-domain shift."
    )
    lines.append(
        "- The predicted favela percentage is often larger than the ground-truth favela percentage, indicating overprediction."
    )
    lines.append(
        "- Performance improves as label density increases, so tiny and low-density patches should be reported separately."
    )
    lines.append(
        "- Hard-negative mining is justified because the model confuses dense built-up texture with favela-like regions."
    )

    lines.append("")
    lines.append("## Label-density metrics")
    lines.append("")
    lines.append(label_density_metrics.to_markdown(index=False))
    lines.append("")

    lines.append("## Region metrics")
    lines.append("")
    lines.append(region_metrics.to_markdown(index=False))
    lines.append("")

    report_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()

    run_dir: Path = args.run_dir
    output_dir: Path = (
        args.output_dir
        if args.output_dir is not None
        else run_dir / "simplified_diagnostics_224"
    )

    prepare_output_dir(output_dir, overwrite=args.overwrite)

    all_df, metrics_paths = read_all_splits(run_dir=run_dir, splits=args.splits)

    # Save enriched per-patch table.
    enriched_csv = output_dir / "csv" / "simplified_enriched_per_patch_metrics.csv"
    all_df.to_csv(enriched_csv, index=False)

    # Overall split summary.
    summary_by_split = aggregate_metrics(all_df, ["split"])
    summary_by_split = summary_by_split.sort_values("split")
    summary_by_split.to_csv(output_dir / "csv" / "simplified_summary_by_split.csv", index=False)

    # Label-density metrics.
    label_density_metrics = aggregate_metrics(
        all_df,
        ["split", "simple_label_density_bin"],
    )
    label_density_metrics["simple_label_density_bin"] = label_density_metrics[
        "simple_label_density_bin"
    ].astype(str)
    label_density_metrics.to_csv(
        output_dir / "csv" / "simplified_label_density_metrics.csv",
        index=False,
    )

    # Prediction-density metrics.
    prediction_density_metrics = aggregate_metrics(
        all_df,
        ["split", "simple_prediction_density_bin"],
    )
    prediction_density_metrics["simple_prediction_density_bin"] = prediction_density_metrics[
        "simple_prediction_density_bin"
    ].astype(str)
    prediction_density_metrics.to_csv(
        output_dir / "csv" / "simplified_prediction_density_metrics.csv",
        index=False,
    )

    # Region metrics.
    region_metrics = aggregate_metrics(
        all_df,
        ["split", "region"],
    )
    region_metrics.to_csv(
        output_dir / "csv" / "simplified_region_metrics.csv",
        index=False,
    )

    # City metrics.
    city_metrics = aggregate_metrics(
        all_df,
        ["split", "region", "city"],
    )
    city_metrics.to_csv(
        output_dir / "csv" / "simplified_city_metrics.csv",
        index=False,
    )

    # Error-mode fractions by city.
    error_counts = (
        all_df.groupby(
            ["split", "region", "city", "simple_error_group"],
            observed=False,
            dropna=False,
        )
        .size()
        .reset_index(name="n_patches")
    )

    city_totals = (
        all_df.groupby(["split", "region", "city"], observed=False, dropna=False)
        .size()
        .reset_index(name="city_total_patches")
    )

    error_city = error_counts.merge(
        city_totals,
        on=["split", "region", "city"],
        how="left",
    )

    error_city["fraction"] = (
        error_city["n_patches"] / error_city["city_total_patches"]
    )

    error_city.to_csv(
        output_dir / "csv" / "simplified_error_mode_fractions_by_city.csv",
        index=False,
    )

    # Save metadata.
    metadata = {
        "run_dir": str(run_dir),
        "output_dir": str(output_dir),
        "splits": args.splits,
        "metrics_paths": metrics_paths,
        "label_bin_order": LABEL_BIN_ORDER,
        "prediction_bin_order": PRED_BIN_ORDER,
        "error_group_order": ERROR_GROUP_ORDER,
    }

    with (output_dir / "metadata.json").open("w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    figures_dir = output_dir / "figures"

    # Plot 1: label-density IoU by split.
    grouped_bar_plot(
        df=label_density_metrics,
        x_col="simple_label_density_bin",
        y_col="global_iou_favela",
        group_col="split",
        x_order=LABEL_BIN_ORDER,
        title="Simplified global favela IoU by label-density bin",
        ylabel="Global favela IoU",
        out_path=figures_dir / "simplified_label_density_global_iou_favela.png",
    )

    # Plot 2: label-density patch counts by split.
    grouped_bar_plot(
        df=label_density_metrics,
        x_col="simple_label_density_bin",
        y_col="n_patches",
        group_col="split",
        x_order=LABEL_BIN_ORDER,
        title="Number of patches by simplified label-density bin",
        ylabel="Number of patches",
        out_path=figures_dir / "simplified_label_density_patch_count.png",
    )

    # Plot 3: prediction-density patch counts by split.
    grouped_bar_plot(
        df=prediction_density_metrics,
        x_col="simple_prediction_density_bin",
        y_col="n_patches",
        group_col="split",
        x_order=PRED_BIN_ORDER,
        title="Number of patches by simplified prediction-density bin",
        ylabel="Number of patches",
        out_path=figures_dir / "simplified_prediction_density_patch_count.png",
    )

    # Plot 4: region IoU with GT density annotation, one per split.
    for split in args.splits:
        split_region = region_metrics[region_metrics["split"] == split].copy()

        if split_region.empty:
            continue

        split_region = split_region.sort_values(
            "global_iou_favela",
            ascending=False,
        )

        simple_bar_plot(
            df=split_region,
            x_col="region",
            y_col="global_iou_favela",
            title=f"Global favela IoU by region ({split})\nNumbers above bars = mean GT favela %",
            ylabel="Global favela IoU",
            out_path=figures_dir / f"simplified_region_global_iou_favela_{split}.png",
            annotate_col="mean_gt_pos_pct",
        )

    # Plot 5: simplified error modes by city, one per split.
    for split in args.splits:
        stacked_error_by_city_plot(
            error_city_df=error_city,
            split=split,
            out_path=figures_dir / f"simplified_error_mode_fraction_by_city_{split}.png",
        )

    create_report(
        output_dir=output_dir,
        metrics_paths=metrics_paths,
        summary_by_split=summary_by_split,
        label_density_metrics=label_density_metrics,
        region_metrics=region_metrics,
    )

    print("\nDone. Simplified diagnostics written to:")
    print(f"  {output_dir}")
    print("\nMain outputs:")
    print(f"  {output_dir / 'simplified_diagnostic_report.md'}")
    print(f"  {output_dir / 'csv'}")
    print(f"  {output_dir / 'figures'}")


if __name__ == "__main__":
    main()