#!/usr/bin/env python3
"""
SNAP-based Sentinel-1 GRD terrain-corrected preprocessing.

This script implements the Sentinel-1 part of:

    Instance B: standard remote-sensing dataset

It expects full Sentinel-1 SAFE products, not only VV.tif / VH.tif files.

Input requirements
------------------
1. A SAFE inventory generated by:

    src/favela_postprocessing/07a_build_s1_safe_inventory.py

Expected inventory path:

    <output_root>/metadata/s1_safe_inventory.csv

2. Full Sentinel-1 SAFE products for the cities to process.

3. ESA SNAP installed, with GPT available either:
    - in PATH as gpt / gpt.exe
    - via --gpt-path
    - via environment variable SNAP_GPT
    - via config key snap_gpt_path

4. A Sentinel-2 reference grid, preferably from:

    <output_root>/dataset_instances/instance_B_standard_rs/s2/<city>/
        <city>_s2_12bands_reflectance_10m.tif

Fallback reference:

    <output_root>/s2_final/<city>/<city>_s2_allbands_10m.tif

Processing chain
----------------
For each SAFE-ready city:

    Read
    Apply-Orbit-File
    ThermalNoiseRemoval
    Calibration to Sigma0 VV/VH, linear scale
    Terrain-Correction
    Write temporary GeoTIFF

Then Python/rasterio:

    Read SNAP terrain-corrected output
    Extract VV and VH
    Align exactly to the Sentinel-2 grid
    Convert linear Sigma0 to dB
    Create VV_minus_VH_dB
    Save final 3-band GeoTIFF

Output
------
Final aligned S1 SNAP product:

    <output_root>/dataset_instances/instance_B_standard_rs/s1_snap/<city>/
        <city>_s1_snap_vv_vh_vvdiff_10m_aligned.tif

Bands:
    1. VV_dB
    2. VH_dB
    3. VV_minus_VH_dB

QC:
    <output_root>/qc/s1_snap_terrain_corrected_qc.csv

Examples
--------
Dry run all cities:

    python src/favela_postprocessing/07_preprocess_s1_snap_terrain_corrected.py --config configs/default.yaml --dry-run

Dry run pilot cities:

    python src/favela_postprocessing/07_preprocess_s1_snap_terrain_corrected.py --config configs/default.yaml --pilot-only --dry-run

Run one city after SAFE is available:

    python src/favela_postprocessing/07_preprocess_s1_snap_terrain_corrected.py --config configs/default.yaml --city rio_de_janeiro --gpt-path "C:/Program Files/esa-snap/bin/gpt.exe"

Force overwrite:

    python src/favela_postprocessing/07_preprocess_s1_snap_terrain_corrected.py --config configs/default.yaml --city rio_de_janeiro --overwrite
"""

from __future__ import annotations

import argparse
import math
import os
import shutil
import subprocess
import tempfile
import xml.dom.minidom
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import rasterio
import yaml
from rasterio.enums import Resampling
from rasterio.warp import reproject
from tqdm import tqdm


SCRIPT_NAME = "07_preprocess_s1_snap_terrain_corrected.py"
INSTANCE_NAME = "instance_B_standard_rs"

PILOT_CITIES = [
    "rio_de_janeiro",
    "belem",
    "porto_alegre",
]

DEFAULT_OUTPUT_NODATA = -9999.0
DEFAULT_MIN_LINEAR_BACKSCATTER = 1e-8


@dataclass
class BandStats:
    band_name: str
    valid_count: int
    invalid_count: int
    min_value: float
    max_value: float
    mean_value: float
    std_value: float
    p2_value: float
    p98_value: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Preprocess Sentinel-1 GRD SAFE products with SNAP and align to S2 grid."
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("configs/default.yaml"),
        help="Path to YAML config file. Default: configs/default.yaml",
    )
    parser.add_argument(
        "--safe-inventory",
        type=Path,
        default=None,
        help=(
            "Path to s1_safe_inventory.csv. "
            "Default: <output_root>/metadata/s1_safe_inventory.csv"
        ),
    )
    parser.add_argument(
        "--gpt-path",
        type=Path,
        default=None,
        help="Path to SNAP GPT executable, e.g. C:/Program Files/esa-snap/bin/gpt.exe",
    )
    parser.add_argument(
        "--city",
        action="append",
        default=None,
        help="Process only one city. Can be repeated.",
    )
    parser.add_argument(
        "--pilot-only",
        action="store_true",
        help="Only process rio_de_janeiro, belem, and porto_alegre.",
    )
    parser.add_argument(
        "--target-resolution",
        type=float,
        default=10.0,
        help="Target SNAP terrain-correction pixel spacing in meters. Default: 10.0",
    )
    parser.add_argument(
        "--dem-name",
        type=str,
        default="SRTM 1Sec HGT",
        help="DEM name passed to SNAP Terrain-Correction. Default: SRTM 1Sec HGT",
    )
    parser.add_argument(
        "--polarizations",
        type=str,
        default="VV,VH",
        help="Comma-separated polarizations to process. Default: VV,VH",
    )
    parser.add_argument(
        "--snap-cache",
        type=str,
        default=None,
        help="Optional GPT cache size, e.g. 4096M or 8G.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate inputs and write QC, but do not run SNAP or write final rasters.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing outputs, overriding config overwrite:false.",
    )
    parser.add_argument(
        "--keep-snap-temp",
        action="store_true",
        help="Keep temporary SNAP terrain-corrected GeoTIFF outputs.",
    )
    return parser.parse_args()


def load_config(config_path: Path) -> Dict[str, Any]:
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with config_path.open("r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f) or {}

    if "output_root" not in cfg:
        raise KeyError("Missing required key in config: output_root")

    return cfg


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def normalize_city_name(value: str) -> str:
    return (
        str(value)
        .strip()
        .lower()
        .replace("-", "_")
        .replace(" ", "_")
        .replace("__", "_")
    )


def discover_gpt_path(cfg: Dict[str, Any], cli_gpt_path: Optional[Path]) -> Optional[Path]:
    candidates: List[Path] = []

    if cli_gpt_path:
        candidates.append(cli_gpt_path)

    env_gpt = os.environ.get("SNAP_GPT")
    if env_gpt:
        candidates.append(Path(env_gpt))

    if cfg.get("snap_gpt_path"):
        candidates.append(Path(str(cfg["snap_gpt_path"])))

    which_gpt = shutil.which("gpt") or shutil.which("gpt.exe")
    if which_gpt:
        candidates.append(Path(which_gpt))

    candidates.extend(
        [
            Path("C:/Program Files/esa-snap/bin/gpt.exe"),
            Path("C:/Program Files/snap/bin/gpt.exe"),
            Path("C:/Program Files/ESA SNAP/bin/gpt.exe"),
            Path("/usr/local/snap/bin/gpt"),
            Path("/opt/snap/bin/gpt"),
            Path("/usr/bin/gpt"),
        ]
    )

    for candidate in candidates:
        try:
            if candidate.exists() and candidate.is_file():
                return candidate
        except OSError:
            continue

    return None


def load_safe_inventory(inventory_path: Path) -> pd.DataFrame:
    if not inventory_path.exists():
        raise FileNotFoundError(
            f"SAFE inventory not found: {inventory_path}\n"
            "Run 07a first:\n"
            "python src/favela_postprocessing/07a_build_s1_safe_inventory.py --config configs/default.yaml"
        )

    df = pd.read_csv(inventory_path)

    required = ["city", "status", "safe_path", "safe_is_valid_for_snap"]
    missing = [col for col in required if col not in df.columns]

    if missing:
        raise KeyError(
            f"SAFE inventory is missing required columns: {missing}\n"
            f"Inventory path: {inventory_path}"
        )

    df["city"] = df["city"].map(normalize_city_name)

    return df


def filter_inventory(
    df: pd.DataFrame,
    selected_cities: Optional[Sequence[str]],
    pilot_only: bool,
) -> pd.DataFrame:
    out = df.copy()

    if pilot_only:
        cities = set(PILOT_CITIES)
        out = out[out["city"].isin(cities)]

    if selected_cities:
        cities = set(normalize_city_name(city) for city in selected_cities)
        out = out[out["city"].isin(cities)]

    out = out.sort_values("city").reset_index(drop=True)

    return out


def bool_from_any(value: Any) -> bool:
    if isinstance(value, bool):
        return value

    if isinstance(value, (int, float)):
        return bool(value)

    value_str = str(value).strip().lower()

    return value_str in {"true", "1", "yes", "y"}


def get_s2_reference_path(output_root: Path, city: str) -> Optional[Path]:
    instance_b_s2 = (
        output_root
        / "dataset_instances"
        / INSTANCE_NAME
        / "s2"
        / city
        / f"{city}_s2_12bands_reflectance_10m.tif"
    )

    if instance_b_s2.exists():
        return instance_b_s2

    finalized_s2 = output_root / "s2_final" / city / f"{city}_s2_allbands_10m.tif"

    if finalized_s2.exists():
        return finalized_s2

    return None


def get_final_output_path(output_root: Path, city: str) -> Path:
    return (
        output_root
        / "dataset_instances"
        / INSTANCE_NAME
        / "s1_snap"
        / city
        / f"{city}_s1_snap_vv_vh_vvdiff_10m_aligned.tif"
    )


def get_graph_path(output_root: Path, city: str) -> Path:
    return (
        output_root
        / "dataset_instances"
        / INSTANCE_NAME
        / "s1_snap"
        / "_snap_graphs"
        / f"{city}_s1_snap_preprocessing_graph.xml"
    )


def get_snap_temp_output_path(output_root: Path, city: str) -> Path:
    return (
        output_root
        / "dataset_instances"
        / INSTANCE_NAME
        / "s1_snap"
        / "_snap_work"
        / city
        / f"{city}_snap_tc_sigma0_linear.tif"
    )


def make_xml_text(element: ET.Element) -> str:
    rough = ET.tostring(element, encoding="utf-8")
    parsed = xml.dom.minidom.parseString(rough)
    return parsed.toprettyxml(indent="  ")


def add_text(parent: ET.Element, tag: str, text: Any) -> ET.Element:
    elem = ET.SubElement(parent, tag)
    elem.text = str(text)
    return elem


def add_node(
    graph: ET.Element,
    node_id: str,
    operator: str,
    source_ref: Optional[str],
    parameters: Dict[str, Any],
) -> ET.Element:
    node = ET.SubElement(graph, "node", {"id": node_id})
    add_text(node, "operator", operator)

    sources = ET.SubElement(node, "sources")
    if source_ref is not None:
        add_text(sources, "sourceProduct", source_ref).set("refid", source_ref)

    params = ET.SubElement(node, "parameters")
    for key, value in parameters.items():
        add_text(params, key, value)

    return node


def build_snap_graph_xml(
    safe_path: Path,
    snap_output_path: Path,
    dem_name: str,
    target_resolution: float,
    polarizations: str,
) -> str:
    """
    Build a SNAP GPT XML graph.

    The graph writes linear Sigma0 terrain-corrected VV/VH to GeoTIFF.
    Python then converts to dB and aligns exactly to the S2 grid.
    """
    graph = ET.Element("graph", {"id": "S1_GRD_TC"})
    add_text(graph, "version", "1.0")

    add_node(
        graph=graph,
        node_id="Read",
        operator="Read",
        source_ref=None,
        parameters={
            "file": str(safe_path),
        },
    )

    add_node(
        graph=graph,
        node_id="Apply-Orbit-File",
        operator="Apply-Orbit-File",
        source_ref="Read",
        parameters={
            "orbitType": "Sentinel Precise (Auto Download)",
            "polyDegree": "3",
            "continueOnFail": "true",
        },
    )

    add_node(
        graph=graph,
        node_id="ThermalNoiseRemoval",
        operator="ThermalNoiseRemoval",
        source_ref="Apply-Orbit-File",
        parameters={
            "selectedPolarisations": polarizations,
            "removeThermalNoise": "true",
            "reIntroduceThermalNoise": "false",
        },
    )

    add_node(
        graph=graph,
        node_id="Calibration",
        operator="Calibration",
        source_ref="ThermalNoiseRemoval",
        parameters={
            "sourceBands": "",
            "auxFile": "Product Auxiliary File",
            "externalAuxFile": "",
            "outputImageInComplex": "false",
            "outputImageScaleInDb": "false",
            "createGammaBand": "false",
            "createBetaBand": "false",
            "selectedPolarisations": polarizations,
            "outputSigmaBand": "true",
            "outputGammaBand": "false",
            "outputBetaBand": "false",
        },
    )

    add_node(
        graph=graph,
        node_id="Terrain-Correction",
        operator="Terrain-Correction",
        source_ref="Calibration",
        parameters={
            "sourceBands": "Sigma0_VV,Sigma0_VH",
            "demName": dem_name,
            "externalDEMFile": "",
            "externalDEMNoDataValue": "0.0",
            "externalDEMApplyEGM": "true",
            "demResamplingMethod": "BILINEAR_INTERPOLATION",
            "imgResamplingMethod": "BILINEAR_INTERPOLATION",
            "pixelSpacingInMeter": str(target_resolution),
            "pixelSpacingInDegree": "0.0",
            "mapProjection": "",
            "alignToStandardGrid": "false",
            "standardGridOriginX": "0.0",
            "standardGridOriginY": "0.0",
            "nodataValueAtSea": "false",
            "saveDEM": "false",
            "saveLatLon": "false",
            "saveIncidenceAngleFromEllipsoid": "false",
            "saveLocalIncidenceAngle": "false",
            "saveProjectedLocalIncidenceAngle": "false",
            "saveSelectedSourceBand": "true",
            "outputComplex": "false",
            "applyRadiometricNormalization": "false",
            "saveSigmaNought": "false",
            "saveGammaNought": "false",
            "saveBetaNought": "false",
            "incidenceAngleForSigma0": "Use projected local incidence angle from DEM",
            "incidenceAngleForGamma0": "Use projected local incidence angle from DEM",
            "auxFile": "Latest Auxiliary File",
        },
    )

    add_node(
        graph=graph,
        node_id="Write",
        operator="Write",
        source_ref="Terrain-Correction",
        parameters={
            "file": str(snap_output_path),
            "formatName": "GeoTIFF-BigTIFF",
        },
    )

    return make_xml_text(graph)


def write_snap_graph(
    graph_path: Path,
    safe_path: Path,
    snap_output_path: Path,
    dem_name: str,
    target_resolution: float,
    polarizations: str,
) -> None:
    ensure_dir(graph_path.parent)
    ensure_dir(snap_output_path.parent)

    xml_text = build_snap_graph_xml(
        safe_path=safe_path,
        snap_output_path=snap_output_path,
        dem_name=dem_name,
        target_resolution=target_resolution,
        polarizations=polarizations,
    )

    graph_path.write_text(xml_text, encoding="utf-8")


def run_snap_gpt(
    gpt_path: Path,
    graph_path: Path,
    snap_cache: Optional[str],
) -> Tuple[int, str, str]:
    cmd = [str(gpt_path), str(graph_path)]

    if snap_cache:
        cmd.extend(["-c", snap_cache])

    proc = subprocess.run(
        cmd,
        check=False,
        capture_output=True,
        text=True,
    )

    return proc.returncode, proc.stdout, proc.stderr


def find_band_index_by_name(
    src: rasterio.io.DatasetReader,
    wanted: str,
    fallback_index: int,
) -> int:
    wanted_lower = wanted.lower()

    for index, desc in enumerate(src.descriptions, start=1):
        if desc and wanted_lower in desc.lower():
            return index

    for index in range(1, src.count + 1):
        tags = src.tags(index)
        text = " ".join(str(v) for v in tags.values()).lower()
        if wanted_lower in text:
            return index

    if src.count >= fallback_index:
        return fallback_index

    raise RuntimeError(
        f"Could not find {wanted} band in SNAP output. "
        f"Band count={src.count}, descriptions={src.descriptions}"
    )


def linear_to_db(
    arr: np.ndarray,
    nodata: float,
    min_linear: float,
) -> np.ndarray:
    out = np.full(arr.shape, nodata, dtype="float32")

    valid = np.isfinite(arr) & (arr > 0)

    if valid.any():
        clipped = np.maximum(arr[valid].astype("float32", copy=False), np.float32(min_linear))
        out[valid] = 10.0 * np.log10(clipped)

    return out


def array_stats(arr: np.ndarray, nodata: float, band_name: str) -> BandStats:
    valid = np.isfinite(arr) & (arr != nodata)
    invalid = ~valid

    valid_count = int(valid.sum())
    invalid_count = int(invalid.sum())

    if valid_count == 0:
        return BandStats(
            band_name=band_name,
            valid_count=0,
            invalid_count=invalid_count,
            min_value=math.nan,
            max_value=math.nan,
            mean_value=math.nan,
            std_value=math.nan,
            p2_value=math.nan,
            p98_value=math.nan,
        )

    values = arr[valid].astype("float32", copy=False)

    return BandStats(
        band_name=band_name,
        valid_count=valid_count,
        invalid_count=invalid_count,
        min_value=float(np.min(values)),
        max_value=float(np.max(values)),
        mean_value=float(np.mean(values)),
        std_value=float(np.std(values)),
        p2_value=float(np.percentile(values, 2)),
        p98_value=float(np.percentile(values, 98)),
    )


def make_temp_output_path(final_path: Path) -> Path:
    ensure_dir(final_path.parent)

    handle = tempfile.NamedTemporaryFile(
        prefix=f".{final_path.stem}_",
        suffix=".tmp.tif",
        dir=final_path.parent,
        delete=False,
    )
    temp_path = Path(handle.name)
    handle.close()

    return temp_path


def align_snap_to_s2_and_write(
    city: str,
    snap_output_path: Path,
    s2_reference_path: Path,
    final_output_path: Path,
    compress: bool,
    overwrite: bool,
    min_linear: float = DEFAULT_MIN_LINEAR_BACKSCATTER,
    output_nodata: float = DEFAULT_OUTPUT_NODATA,
) -> List[Dict[str, Any]]:
    if final_output_path.exists() and not overwrite:
        return [
            {
                "city": city,
                "status": "SKIPPED_EXISTS",
                "snap_output_path": str(snap_output_path),
                "s2_reference_path": str(s2_reference_path),
                "final_output_path": str(final_output_path),
            }
        ]

    if not snap_output_path.exists():
        return [
            {
                "city": city,
                "status": "FAILED_MISSING_SNAP_OUTPUT",
                "snap_output_path": str(snap_output_path),
                "s2_reference_path": str(s2_reference_path),
                "final_output_path": str(final_output_path),
            }
        ]

    temp_path: Optional[Path] = None

    try:
        with rasterio.open(s2_reference_path) as s2_ref:
            dst_crs = s2_ref.crs
            dst_transform = s2_ref.transform
            dst_height = s2_ref.height
            dst_width = s2_ref.width

            if dst_crs is None:
                raise RuntimeError(f"S2 reference has no CRS: {s2_reference_path}")

            with rasterio.open(snap_output_path) as src:
                if src.crs is None:
                    raise RuntimeError(f"SNAP output has no CRS: {snap_output_path}")

                vv_index = find_band_index_by_name(src, "VV", fallback_index=1)
                vh_index = find_band_index_by_name(src, "VH", fallback_index=2)

                vv_linear_aligned = np.full(
                    (dst_height, dst_width),
                    np.nan,
                    dtype="float32",
                )
                vh_linear_aligned = np.full(
                    (dst_height, dst_width),
                    np.nan,
                    dtype="float32",
                )

                src_nodata = src.nodata

                reproject(
                    source=rasterio.band(src, vv_index),
                    destination=vv_linear_aligned,
                    src_transform=src.transform,
                    src_crs=src.crs,
                    src_nodata=src_nodata,
                    dst_transform=dst_transform,
                    dst_crs=dst_crs,
                    dst_nodata=np.nan,
                    resampling=Resampling.bilinear,
                )

                reproject(
                    source=rasterio.band(src, vh_index),
                    destination=vh_linear_aligned,
                    src_transform=src.transform,
                    src_crs=src.crs,
                    src_nodata=src_nodata,
                    dst_transform=dst_transform,
                    dst_crs=dst_crs,
                    dst_nodata=np.nan,
                    resampling=Resampling.bilinear,
                )

                vv_db = linear_to_db(vv_linear_aligned, output_nodata, min_linear)
                vh_db = linear_to_db(vh_linear_aligned, output_nodata, min_linear)

                both_valid = (
                    np.isfinite(vv_db)
                    & np.isfinite(vh_db)
                    & (vv_db != output_nodata)
                    & (vh_db != output_nodata)
                )

                vv_minus_vh = np.full((dst_height, dst_width), output_nodata, dtype="float32")
                vv_minus_vh[both_valid] = vv_db[both_valid] - vh_db[both_valid]

                output_stack = np.stack([vv_db, vh_db, vv_minus_vh], axis=0).astype("float32")

                profile = s2_ref.profile.copy()
                profile.update(
                    driver="GTiff",
                    dtype="float32",
                    count=3,
                    nodata=output_nodata,
                    BIGTIFF="IF_SAFER",
                )
                profile.pop("photometric", None)

                if compress:
                    profile.update(compress="DEFLATE", predictor=3)
                else:
                    profile.pop("compress", None)
                    profile.pop("predictor", None)

                if dst_width >= 512 and dst_height >= 512:
                    profile.update(tiled=True, blockxsize=512, blockysize=512)

                temp_path = make_temp_output_path(final_output_path)

                with rasterio.open(temp_path, "w", **profile) as dst:
                    dst.write(output_stack)
                    dst.set_band_description(1, "VV_dB")
                    dst.set_band_description(2, "VH_dB")
                    dst.set_band_description(3, "VV_minus_VH_dB")
                    dst.update_tags(
                        city=city,
                        processing_script=SCRIPT_NAME,
                        dataset_instance=INSTANCE_NAME,
                        source_snap_output=str(snap_output_path),
                        s2_reference_grid=str(s2_reference_path),
                        output_units="dB",
                        bands="VV_dB,VH_dB,VV_minus_VH_dB",
                    )

                temp_path.replace(final_output_path)

                stats = [
                    array_stats(vv_db, output_nodata, "VV_dB"),
                    array_stats(vh_db, output_nodata, "VH_dB"),
                    array_stats(vv_minus_vh, output_nodata, "VV_minus_VH_dB"),
                ]

                rows: List[Dict[str, Any]] = []

                for band_number, stat in enumerate(stats, start=1):
                    rows.append(
                        {
                            "city": city,
                            "status": "OK",
                            "band": band_number,
                            "band_name": stat.band_name,
                            "snap_output_path": str(snap_output_path),
                            "s2_reference_path": str(s2_reference_path),
                            "final_output_path": str(final_output_path),
                            "snap_band_vv_index": vv_index,
                            "snap_band_vh_index": vh_index,
                            "snap_crs": str(src.crs),
                            "s2_crs": str(dst_crs),
                            "output_crs": str(dst_crs),
                            "output_width": dst_width,
                            "output_height": dst_height,
                            "output_transform": str(dst_transform),
                            "output_nodata": output_nodata,
                            "valid_count": stat.valid_count,
                            "invalid_count": stat.invalid_count,
                            "min": stat.min_value,
                            "max": stat.max_value,
                            "mean": stat.mean_value,
                            "std": stat.std_value,
                            "p2": stat.p2_value,
                            "p98": stat.p98_value,
                        }
                    )

                return rows

    except Exception as exc:
        if temp_path is not None and temp_path.exists():
            temp_path.unlink(missing_ok=True)

        return [
            {
                "city": city,
                "status": "FAILED_ALIGN_OR_WRITE",
                "snap_output_path": str(snap_output_path),
                "s2_reference_path": str(s2_reference_path),
                "final_output_path": str(final_output_path),
                "error": repr(exc),
            }
        ]


def process_city(
    row: pd.Series,
    output_root: Path,
    gpt_path: Optional[Path],
    compress: bool,
    overwrite: bool,
    dry_run: bool,
    keep_snap_temp: bool,
    dem_name: str,
    target_resolution: float,
    polarizations: str,
    snap_cache: Optional[str],
) -> List[Dict[str, Any]]:
    city = normalize_city_name(row["city"])

    final_output_path = get_final_output_path(output_root, city)
    graph_path = get_graph_path(output_root, city)
    snap_output_path = get_snap_temp_output_path(output_root, city)
    s2_reference_path = get_s2_reference_path(output_root, city)

    inventory_status = str(row.get("status", ""))
    safe_is_valid = bool_from_any(row.get("safe_is_valid_for_snap", False))
    safe_path_value = str(row.get("safe_path", "")).strip()
    safe_path = Path(safe_path_value) if safe_path_value else None

    base_row = {
        "city": city,
        "inventory_status": inventory_status,
        "safe_path": safe_path_value,
        "graph_path": str(graph_path),
        "snap_output_path": str(snap_output_path),
        "final_output_path": str(final_output_path),
        "s2_reference_path": str(s2_reference_path) if s2_reference_path else "",
    }

    if final_output_path.exists() and not overwrite:
        out = dict(base_row)
        out.update({"status": "SKIPPED_EXISTS"})
        return [out]

    if s2_reference_path is None:
        out = dict(base_row)
        out.update(
            {
                "status": "SKIPPED_MISSING_S2_REFERENCE",
                "recommendation": "Create/check S2 finalized or instance_B_standard_rs S2 product first.",
            }
        )
        return [out]

    if not safe_is_valid or safe_path is None or not safe_path.exists():
        out = dict(base_row)
        out.update(
            {
                "status": "SKIPPED_NO_VALID_SAFE",
                "recommendation": (
                    "Download or locate the full Sentinel-1 .SAFE product, then rerun 07a inventory."
                ),
            }
        )
        return [out]

    if gpt_path is None:
        out = dict(base_row)
        out.update(
            {
                "status": "SKIPPED_MISSING_SNAP_GPT",
                "recommendation": (
                    "Install ESA SNAP and pass --gpt-path, or set SNAP_GPT environment variable."
                ),
            }
        )
        return [out]

    if dry_run:
        out = dict(base_row)
        out.update(
            {
                "status": "DRY_RUN_READY",
                "gpt_path": str(gpt_path),
                "dem_name": dem_name,
                "target_resolution": target_resolution,
                "polarizations": polarizations,
            }
        )
        return [out]

    try:
        write_snap_graph(
            graph_path=graph_path,
            safe_path=safe_path,
            snap_output_path=snap_output_path,
            dem_name=dem_name,
            target_resolution=target_resolution,
            polarizations=polarizations,
        )

        return_code, stdout, stderr = run_snap_gpt(
            gpt_path=gpt_path,
            graph_path=graph_path,
            snap_cache=snap_cache,
        )

        stdout_path = graph_path.with_suffix(".stdout.txt")
        stderr_path = graph_path.with_suffix(".stderr.txt")

        stdout_path.write_text(stdout or "", encoding="utf-8")
        stderr_path.write_text(stderr or "", encoding="utf-8")

        if return_code != 0:
            out = dict(base_row)
            out.update(
                {
                    "status": "FAILED_SNAP_GPT",
                    "gpt_path": str(gpt_path),
                    "gpt_return_code": return_code,
                    "gpt_stdout_path": str(stdout_path),
                    "gpt_stderr_path": str(stderr_path),
                    "error": "SNAP GPT returned a non-zero exit code.",
                }
            )
            return [out]

        rows = align_snap_to_s2_and_write(
            city=city,
            snap_output_path=snap_output_path,
            s2_reference_path=s2_reference_path,
            final_output_path=final_output_path,
            compress=compress,
            overwrite=overwrite,
        )

        for out in rows:
            out.update(
                {
                    "inventory_status": inventory_status,
                    "safe_path": safe_path_value,
                    "graph_path": str(graph_path),
                    "gpt_path": str(gpt_path),
                    "gpt_return_code": return_code,
                    "gpt_stdout_path": str(stdout_path),
                    "gpt_stderr_path": str(stderr_path),
                    "dem_name": dem_name,
                    "target_resolution": target_resolution,
                    "polarizations": polarizations,
                }
            )

        if not keep_snap_temp and snap_output_path.exists():
            snap_output_path.unlink(missing_ok=True)

        return rows

    except Exception as exc:
        out = dict(base_row)
        out.update(
            {
                "status": "FAILED_UNEXPECTED",
                "gpt_path": str(gpt_path) if gpt_path else "",
                "error": repr(exc),
            }
        )
        return [out]


def write_qc(rows: Sequence[Dict[str, Any]], qc_path: Path) -> None:
    ensure_dir(qc_path.parent)

    df = pd.DataFrame(rows)
    df.to_csv(qc_path, index=False)

    print(f"[INFO] Wrote QC CSV: {qc_path}")

    if "status" in df.columns:
        print("[INFO] Status counts:")
        print(df["status"].value_counts(dropna=False).to_string())

    if "city" in df.columns and "status" in df.columns:
        ok_cities = df.loc[df["status"] == "OK", "city"].nunique()
        print(f"[INFO] SNAP S1 cities successfully processed: {ok_cities}")


def main() -> int:
    args = parse_args()
    cfg = load_config(args.config)

    output_root = Path(str(cfg["output_root"]))

    safe_inventory_path = (
        args.safe_inventory
        if args.safe_inventory is not None
        else output_root / "metadata" / "s1_safe_inventory.csv"
    )

    qc_path = output_root / "qc" / "s1_snap_terrain_corrected_qc.csv"

    compress = bool(cfg.get("compress", True))
    overwrite = bool(cfg.get("overwrite", False)) or bool(args.overwrite)

    gpt_path = discover_gpt_path(cfg, args.gpt_path)

    print("[INFO] Sentinel-1 SNAP terrain-corrected preprocessing")
    print(f"[INFO] Script: {SCRIPT_NAME}")
    print(f"[INFO] Config: {args.config}")
    print(f"[INFO] Output root: {output_root}")
    print(f"[INFO] SAFE inventory: {safe_inventory_path}")
    print(f"[INFO] QC CSV: {qc_path}")
    print(f"[INFO] Compress: {compress}")
    print(f"[INFO] Overwrite: {overwrite}")
    print(f"[INFO] Dry run: {args.dry_run}")
    print(f"[INFO] GPT path: {gpt_path if gpt_path else 'NOT FOUND'}")
    print(f"[INFO] DEM name: {args.dem_name}")
    print(f"[INFO] Target resolution: {args.target_resolution}")
    print(f"[INFO] Polarizations: {args.polarizations}")

    inventory_df = load_safe_inventory(safe_inventory_path)
    inventory_df = filter_inventory(
        inventory_df,
        selected_cities=args.city,
        pilot_only=args.pilot_only,
    )

    print(f"[INFO] Cities selected from inventory: {len(inventory_df)}")

    all_rows: List[Dict[str, Any]] = []

    for _, row in tqdm(inventory_df.iterrows(), total=len(inventory_df), desc="SNAP S1 cities"):
        rows = process_city(
            row=row,
            output_root=output_root,
            gpt_path=gpt_path,
            compress=compress,
            overwrite=overwrite,
            dry_run=args.dry_run,
            keep_snap_temp=args.keep_snap_temp,
            dem_name=args.dem_name,
            target_resolution=args.target_resolution,
            polarizations=args.polarizations,
            snap_cache=args.snap_cache,
        )

        all_rows.extend(rows)

        city = normalize_city_name(row["city"])
        statuses = sorted(set(str(item.get("status")) for item in rows))
        print(f"[INFO] {city}: {', '.join(statuses)}")

    write_qc(all_rows, qc_path)

    statuses = {str(row.get("status")) for row in all_rows}

    if any(status.startswith("FAILED") for status in statuses):
        print("[ERROR] Some cities failed. Check the QC CSV and SNAP logs.")
        return 1

    if "OK" not in statuses:
        print("[WARN] No SNAP S1 products were created.")
        print("[WARN] This is expected if no SAFE products are available yet.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())