#!/usr/bin/env python3
"""
Compute valid crop windows for removing border-connected Sentinel-2 nodata.

This script reads the full-resolution S2 nodata masks and computes a rectangular
crop window that excludes border-connected nodata as much as possible.

It does not modify rasters.

Inputs:
- city-level S2 rasters
- repair plan CSV from 02_build_s2_nodata_repair_plan.py

Outputs:
- city_s2_valid_crop_windows.csv
- city_s2_valid_crop_windows.json
- city_s2_valid_crop_windows.md

The crop window is expressed in original S2 pixel coordinates:

    row_start, row_stop, col_start, col_stop

The same window must later be applied to:
- S2
- S1 SNAP
- labels

Important:
The script allows internal nodata to remain inside the crop. Internal nodata
will be handled later by a fill/recomposition step. The purpose here is only
to remove border/footprint nodata.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import deque
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd
import rasterio


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compute valid S2 crop windows that remove border-connected nodata."
    )

    parser.add_argument(
        "--s2-root",
        type=str,
        required=True,
        help=(
            "Root folder containing city S2 rasters, e.g. "
            "D:/post_processing_dataset/dataset_instances/instance_B_standard_rs/s2"
        ),
    )

    parser.add_argument(
        "--repair-plan",
        type=str,
        required=True,
        help="CSV generated by 02_build_s2_nodata_repair_plan.py.",
    )

    parser.add_argument(
        "--output-dir",
        type=str,
        required=True,
        help="Directory where crop-window reports will be written.",
    )

    parser.add_argument(
        "--cities",
        nargs="*",
        default=None,
        help="Optional list of city slugs. If omitted, all cities in the repair plan are processed.",
    )

    zero_group = parser.add_mutually_exclusive_group()
    zero_group.add_argument(
        "--all-zero-as-nodata",
        dest="all_zero_as_nodata",
        action="store_true",
        help="Treat pixels where all bands are exactly zero as nodata.",
    )
    zero_group.add_argument(
        "--no-all-zero-as-nodata",
        dest="all_zero_as_nodata",
        action="store_false",
        help="Do not treat all-zero-all-band pixels as nodata.",
    )
    parser.set_defaults(all_zero_as_nodata=True)

    nan_group = parser.add_mutually_exclusive_group()
    nan_group.add_argument(
        "--nan-as-nodata",
        dest="nan_as_nodata",
        action="store_true",
        help="Treat NaN/Inf values in any band as nodata.",
    )
    nan_group.add_argument(
        "--no-nan-as-nodata",
        dest="nan_as_nodata",
        action="store_false",
        help="Do not treat NaN/Inf values as nodata.",
    )
    parser.set_defaults(nan_as_nodata=True)

    parser.add_argument(
        "--border-margin",
        type=int,
        default=128,
        help=(
            "Border seed margin in full-resolution pixels. "
            "Nodata connected to this seed zone is treated as border-connected."
        ),
    )

    parser.add_argument(
        "--method",
        choices=["largest_rectangle", "simple_trim"],
        default="largest_rectangle",
        help=(
            "Crop strategy. largest_rectangle is stricter and preserves the largest "
            "rectangle without original border-connected nodata. simple_trim is faster "
            "but may be less optimal."
        ),
    )

    parser.add_argument(
        "--min-retained-percent",
        type=float,
        default=50.0,
        help="Warn if the computed crop retains less than this percentage of the original raster.",
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing outputs.",
    )

    return parser.parse_args()


def percent(count: int | float, total: int | float) -> float:
    if total == 0:
        return 0.0
    return 100.0 * float(count) / float(total)


def find_city_raster(s2_root: Path, city: str) -> Path:
    city_dir = s2_root / city

    patterns = [
        f"{city}_s2_12bands_reflectance_10m.tif",
        f"{city}_s2*.tif",
        "*_s2_12bands_reflectance_10m.tif",
        "*.tif",
    ]

    candidates: list[Path] = []

    if city_dir.exists():
        for pattern in patterns:
            candidates.extend(sorted(city_dir.glob(pattern)))

    if not candidates:
        for pattern in patterns:
            candidates.extend(sorted(s2_root.glob(pattern)))
            candidates.extend(sorted(s2_root.glob(f"*/{pattern}")))

    candidates = [p for p in candidates if p.is_file() and city in p.name]

    if not candidates:
        raise FileNotFoundError(f"No S2 raster found for city '{city}' under {s2_root}")

    exact = [p for p in candidates if p.name == f"{city}_s2_12bands_reflectance_10m.tif"]
    if exact:
        return exact[0]

    return candidates[0]


def build_combined_nodata_mask(
    raster_path: Path,
    all_zero_as_nodata: bool,
    nan_as_nodata: bool,
) -> tuple[np.ndarray, dict]:
    """
    Build full-resolution combined nodata mask.

    combined nodata =
        official mask nodata
        OR all-zero-all-band pixels
        OR non-finite pixels
    """
    with rasterio.open(raster_path) as src:
        height = src.height
        width = src.width
        count = src.count

        combined = np.zeros((height, width), dtype=bool)
        official_nodata = np.zeros((height, width), dtype=bool)
        all_zero_nodata = np.zeros((height, width), dtype=bool)
        nonfinite_nodata = np.zeros((height, width), dtype=bool)

        band_indexes = list(range(1, count + 1))

        for _, window in src.block_windows(1):
            row0 = int(window.row_off)
            row1 = int(window.row_off + window.height)
            col0 = int(window.col_off)
            col1 = int(window.col_off + window.width)

            masks = src.read_masks(indexes=band_indexes, window=window)
            official_block = np.any(masks == 0, axis=0)
            block_combined = official_block

            official_nodata[row0:row1, col0:col1] = official_block

            if all_zero_as_nodata or nan_as_nodata:
                data = src.read(indexes=band_indexes, window=window)

                if all_zero_as_nodata:
                    all_zero_block = np.all(data == 0, axis=0)
                    all_zero_nodata[row0:row1, col0:col1] = all_zero_block
                    block_combined = block_combined | all_zero_block

                if nan_as_nodata:
                    nonfinite_block = np.any(~np.isfinite(data), axis=0)
                    nonfinite_nodata[row0:row1, col0:col1] = nonfinite_block
                    block_combined = block_combined | nonfinite_block

            combined[row0:row1, col0:col1] = block_combined

        meta = {
            "width": width,
            "height": height,
            "band_count": count,
            "dtype": src.dtypes[0],
            "crs": str(src.crs),
            "raster_nodata_value": src.nodata,
            "total_pixels": int(height * width),
            "official_nodata_pixels": int(official_nodata.sum()),
            "all_zero_allbands_pixels": int(all_zero_nodata.sum()),
            "nonfinite_pixels": int(nonfinite_nodata.sum()),
            "combined_nodata_pixels": int(combined.sum()),
        }

    return combined, meta


def classify_border_connected_nodata(
    nodata_mask: np.ndarray,
    border_margin: int,
) -> np.ndarray:
    """
    Return mask of nodata pixels connected to the outer raster margin.
    """
    nodata_mask = nodata_mask.astype(bool, copy=False)
    height, width = nodata_mask.shape

    margin = max(1, int(border_margin))
    margin_rows = min(margin, height)
    margin_cols = min(margin, width)

    seed = np.zeros_like(nodata_mask, dtype=bool)
    seed[:margin_rows, :] = True
    seed[-margin_rows:, :] = True
    seed[:, :margin_cols] = True
    seed[:, -margin_cols:] = True
    seed &= nodata_mask

    try:
        from scipy import ndimage

        return ndimage.binary_propagation(seed, mask=nodata_mask).astype(bool)

    except Exception as exc:
        print(
            "[WARN] scipy.ndimage failed or is unavailable. "
            "Using slower pure-Python BFS. "
            f"Reason: {exc}",
            file=sys.stderr,
        )

    visited = np.zeros_like(nodata_mask, dtype=bool)
    queue: deque[tuple[int, int]] = deque()

    rows, cols = np.where(seed)
    for r, c in zip(rows, cols):
        visited[int(r), int(c)] = True
        queue.append((int(r), int(c)))

    neighbors = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    while queue:
        r, c = queue.popleft()

        for dr, dc in neighbors:
            rr = r + dr
            cc = c + dc

            if rr < 0 or rr >= height or cc < 0 or cc >= width:
                continue

            if visited[rr, cc]:
                continue

            if not nodata_mask[rr, cc]:
                continue

            visited[rr, cc] = True
            queue.append((rr, cc))

    return visited


def largest_rectangle_of_true(mask: np.ndarray) -> tuple[int, int, int, int, int]:
    """
    Find the largest all-True rectangle in a boolean mask.

    Returns:
        row_start, row_stop, col_start, col_stop, area

    row_stop and col_stop are exclusive.
    """
    mask = mask.astype(bool, copy=False)
    height, width = mask.shape

    if height == 0 or width == 0:
        return 0, 0, 0, 0, 0

    if mask.all():
        return 0, height, 0, width, height * width

    heights = np.zeros(width, dtype=np.int32)

    best_area = 0
    best_top = 0
    best_bottom = 0
    best_left = 0
    best_right = 0

    for r in range(height):
        row = mask[r]
        heights[row] += 1
        heights[~row] = 0

        stack: list[tuple[int, int]] = []

        for c in range(width + 1):
            current_height = int(heights[c]) if c < width else 0
            start_col = c

            while stack and stack[-1][1] > current_height:
                prev_col, prev_height = stack.pop()
                area = prev_height * (c - prev_col)

                if area > best_area:
                    best_area = area
                    best_top = r - prev_height + 1
                    best_bottom = r + 1
                    best_left = prev_col
                    best_right = c

                start_col = prev_col

            if not stack or stack[-1][1] < current_height:
                stack.append((start_col, current_height))

    return best_top, best_bottom, best_left, best_right, best_area


def simple_trim_window(forbidden: np.ndarray) -> tuple[int, int, int, int, int]:
    """
    Faster but less optimal crop method.

    It trims rows/columns until no forbidden border-connected nodata remains inside
    the rectangle. This is mainly a fallback if largest_rectangle is too slow.
    """
    height, width = forbidden.shape

    if not forbidden.any():
        return 0, height, 0, width, height * width

    top = 0
    bottom = height
    left = 0
    right = width

    while True:
        sub = forbidden[top:bottom, left:right]

        if not sub.any():
            break

        top_count = int(sub[0, :].sum())
        bottom_count = int(sub[-1, :].sum())
        left_count = int(sub[:, 0].sum())
        right_count = int(sub[:, -1].sum())

        counts = {
            "top": top_count,
            "bottom": bottom_count,
            "left": left_count,
            "right": right_count,
        }

        side = max(counts, key=counts.get)

        if counts[side] == 0:
            # Forbidden pixels exist internally, but no side currently touches them.
            # Fall back to bounding box around forbidden pixels and remove the side
            # that preserves the most area.
            rows, cols = np.where(sub)
            min_r = int(rows.min()) + top
            max_r = int(rows.max()) + top
            min_c = int(cols.min()) + left
            max_c = int(cols.max()) + left

            candidates = []

            if max_r + 1 < bottom:
                candidates.append((max_r + 1, bottom, left, right))
            if min_r > top:
                candidates.append((top, min_r, left, right))
            if max_c + 1 < right:
                candidates.append((top, bottom, max_c + 1, right))
            if min_c > left:
                candidates.append((top, bottom, left, min_c))

            if not candidates:
                return 0, 0, 0, 0, 0

            top, bottom, left, right = max(
                candidates,
                key=lambda x: max(0, x[1] - x[0]) * max(0, x[3] - x[2]),
            )
        else:
            if side == "top":
                top += 1
            elif side == "bottom":
                bottom -= 1
            elif side == "left":
                left += 1
            elif side == "right":
                right -= 1

        if top >= bottom or left >= right:
            return 0, 0, 0, 0, 0

    area = (bottom - top) * (right - left)
    return top, bottom, left, right, area


def recompute_border_internal_inside_crop(
    combined_crop: np.ndarray,
    border_margin: int,
) -> tuple[int, int]:
    """
    Recompute border-connected and internal nodata after crop.

    This is useful because an originally internal nodata cluster could become
    crop-border-connected if the crop window touches it.
    """
    if not combined_crop.any():
        return 0, 0

    border_after = classify_border_connected_nodata(
        nodata_mask=combined_crop,
        border_margin=border_margin,
    )
    internal_after = combined_crop & ~border_after

    return int(border_after.sum()), int(internal_after.sum())


def compute_crop_for_city(
    city: str,
    s2_path: Path,
    recommended_action: str,
    args: argparse.Namespace,
) -> dict:
    combined, meta = build_combined_nodata_mask(
        raster_path=s2_path,
        all_zero_as_nodata=args.all_zero_as_nodata,
        nan_as_nodata=args.nan_as_nodata,
    )

    border_connected = classify_border_connected_nodata(
        nodata_mask=combined,
        border_margin=args.border_margin,
    )

    internal_original = combined & ~border_connected

    height = meta["height"]
    width = meta["width"]
    total_pixels = meta["total_pixels"]

    combined_pixels = int(combined.sum())
    border_pixels = int(border_connected.sum())
    internal_pixels = int(internal_original.sum())

    if recommended_action == "no_action" or border_pixels == 0:
        row_start, row_stop, col_start, col_stop = 0, height, 0, width
        crop_method_used = "full_extent"
        crop_area = height * width
    else:
        eligible = ~border_connected

        if args.method == "largest_rectangle":
            row_start, row_stop, col_start, col_stop, crop_area = largest_rectangle_of_true(eligible)
            crop_method_used = "largest_rectangle"
        else:
            row_start, row_stop, col_start, col_stop, crop_area = simple_trim_window(border_connected)
            crop_method_used = "simple_trim"

    cropped_height = row_stop - row_start
    cropped_width = col_stop - col_start
    cropped_pixels = cropped_height * cropped_width

    if cropped_pixels <= 0:
        crop_status = "failed_no_valid_window"
        retained_percent = 0.0
        removed_percent = 100.0
        post_combined_pixels = 0
        post_original_border_pixels = 0
        post_border_recomputed_pixels = 0
        post_internal_recomputed_pixels = 0
    else:
        combined_crop = combined[row_start:row_stop, col_start:col_stop]
        original_border_crop = border_connected[row_start:row_stop, col_start:col_stop]

        post_combined_pixels = int(combined_crop.sum())
        post_original_border_pixels = int(original_border_crop.sum())

        post_border_recomputed_pixels, post_internal_recomputed_pixels = (
            recompute_border_internal_inside_crop(
                combined_crop=combined_crop,
                border_margin=args.border_margin,
            )
        )

        retained_percent = percent(cropped_pixels, total_pixels)
        removed_percent = 100.0 - retained_percent

        if post_original_border_pixels > 0:
            crop_status = "warning_original_border_nodata_remaining"
        elif retained_percent < args.min_retained_percent:
            crop_status = "warning_large_crop_loss"
        elif post_combined_pixels > 0:
            crop_status = "ok_border_removed_residual_internal_or_crop_edge_nodata"
        else:
            crop_status = "ok_no_s2_nodata_after_crop"

    return {
        "city": city,
        "recommended_action_from_plan": recommended_action,
        "crop_status": crop_status,
        "crop_method": crop_method_used,
        "s2_path": str(s2_path),
        "original_width": width,
        "original_height": height,
        "original_pixels": total_pixels,
        "row_start": row_start,
        "row_stop": row_stop,
        "col_start": col_start,
        "col_stop": col_stop,
        "cropped_width": cropped_width,
        "cropped_height": cropped_height,
        "cropped_pixels": cropped_pixels,
        "retained_pixels_percent": retained_percent,
        "removed_pixels_percent": removed_percent,
        "pre_combined_nodata_pixels": combined_pixels,
        "pre_border_connected_nodata_pixels": border_pixels,
        "pre_internal_nodata_pixels": internal_pixels,
        "pre_combined_nodata_percent": percent(combined_pixels, total_pixels),
        "pre_border_connected_nodata_percent": percent(border_pixels, total_pixels),
        "pre_internal_nodata_percent": percent(internal_pixels, total_pixels),
        "post_crop_combined_nodata_pixels": post_combined_pixels,
        "post_crop_original_border_connected_nodata_pixels": post_original_border_pixels,
        "post_crop_recomputed_border_connected_nodata_pixels": post_border_recomputed_pixels,
        "post_crop_recomputed_internal_nodata_pixels": post_internal_recomputed_pixels,
        "post_crop_combined_nodata_percent_of_crop": percent(post_combined_pixels, cropped_pixels),
        "post_crop_original_border_connected_nodata_percent_of_crop": percent(
            post_original_border_pixels, cropped_pixels
        ),
        "post_crop_recomputed_border_connected_nodata_percent_of_crop": percent(
            post_border_recomputed_pixels, cropped_pixels
        ),
        "post_crop_recomputed_internal_nodata_percent_of_crop": percent(
            post_internal_recomputed_pixels, cropped_pixels
        ),
        "border_margin_pixels": args.border_margin,
        "all_zero_as_nodata": args.all_zero_as_nodata,
        "nan_as_nodata": args.nan_as_nodata,
    }


def write_csv(rows: list[dict], path: Path, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists. Use --overwrite to replace: {path}")

    if not rows:
        raise ValueError("No rows to write.")

    fieldnames = list(rows[0].keys())

    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_json(rows: list[dict], path: Path, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists. Use --overwrite to replace: {path}")

    with path.open("w", encoding="utf-8") as f:
        json.dump(rows, f, indent=2, ensure_ascii=False)


def write_markdown(rows: list[dict], path: Path, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists. Use --overwrite to replace: {path}")

    cols = [
        "city",
        "recommended_action_from_plan",
        "crop_status",
        "retained_pixels_percent",
        "removed_pixels_percent",
        "post_crop_combined_nodata_percent_of_crop",
        "post_crop_original_border_connected_nodata_percent_of_crop",
        "post_crop_recomputed_internal_nodata_percent_of_crop",
        "row_start",
        "row_stop",
        "col_start",
        "col_stop",
    ]

    with path.open("w", encoding="utf-8") as f:
        f.write("# Sentinel-2 valid crop windows\n\n")
        f.write(
            "This report computes crop windows for removing border-connected "
            "S2 nodata. It does not modify rasters.\n\n"
        )

        f.write("## Crop status counts\n\n")
        counts: dict[str, int] = {}
        for row in rows:
            status = row["crop_status"]
            counts[status] = counts.get(status, 0) + 1

        for status, count in sorted(counts.items()):
            f.write(f"- `{status}`: {count}\n")

        f.write("\n## City crop windows\n\n")
        f.write("| " + " | ".join(cols) + " |\n")
        f.write("| " + " | ".join(["---"] * len(cols)) + " |\n")

        for row in rows:
            values = []
            for col in cols:
                value = row[col]
                if isinstance(value, float):
                    value = f"{value:.6f}"
                values.append(str(value))
            f.write("| " + " | ".join(values) + " |\n")


def main() -> None:
    args = parse_args()

    s2_root = Path(args.s2_root)
    repair_plan_path = Path(args.repair_plan)
    output_dir = Path(args.output_dir)

    if not s2_root.exists():
        raise FileNotFoundError(f"S2 root does not exist: {s2_root}")

    if not repair_plan_path.exists():
        raise FileNotFoundError(f"Repair plan CSV does not exist: {repair_plan_path}")

    output_dir.mkdir(parents=True, exist_ok=True)

    plan = pd.read_csv(repair_plan_path)

    required_cols = {"city", "recommended_action"}
    missing_cols = required_cols - set(plan.columns)
    if missing_cols:
        raise ValueError(f"Repair plan is missing required columns: {sorted(missing_cols)}")

    if args.cities:
        plan = plan[plan["city"].isin(args.cities)].copy()

    if plan.empty:
        raise ValueError("No cities to process after applying filters.")

    print(f"[INFO] S2 root: {s2_root}")
    print(f"[INFO] Repair plan: {repair_plan_path}")
    print(f"[INFO] Output dir: {output_dir}")
    print(f"[INFO] Cities to process: {len(plan)}")
    print(f"[INFO] method: {args.method}")
    print(f"[INFO] border_margin: {args.border_margin}")
    print(f"[INFO] all_zero_as_nodata: {args.all_zero_as_nodata}")
    print(f"[INFO] nan_as_nodata: {args.nan_as_nodata}")

    rows: list[dict] = []

    for i, row in enumerate(plan.itertuples(index=False), start=1):
        city = str(getattr(row, "city"))
        recommended_action = str(getattr(row, "recommended_action"))
        s2_path = find_city_raster(s2_root, city)

        print(f"\n[STEP {i}/{len(plan)}] {city}")
        print(f"[INFO] action from plan: {recommended_action}")
        print(f"[INFO] raster: {s2_path}")

        try:
            result = compute_crop_for_city(
                city=city,
                s2_path=s2_path,
                recommended_action=recommended_action,
                args=args,
            )
            rows.append(result)

            print(
                "[OK] "
                f"status={result['crop_status']} | "
                f"retained={result['retained_pixels_percent']:.2f}% | "
                f"removed={result['removed_pixels_percent']:.2f}% | "
                f"post_nodata={result['post_crop_combined_nodata_percent_of_crop']:.6f}% | "
                f"window=rows[{result['row_start']}:{result['row_stop']}], "
                f"cols[{result['col_start']}:{result['col_stop']}]"
            )

        except Exception as exc:
            print(f"[ERROR] Failed city {city}: {exc}", file=sys.stderr)
            rows.append(
                {
                    "city": city,
                    "recommended_action_from_plan": recommended_action,
                    "crop_status": "error",
                    "crop_method": args.method,
                    "s2_path": str(s2_path),
                    "error": str(exc),
                }
            )

    rows = sorted(rows, key=lambda x: str(x["city"]))

    csv_path = output_dir / "city_s2_valid_crop_windows.csv"
    json_path = output_dir / "city_s2_valid_crop_windows.json"
    md_path = output_dir / "city_s2_valid_crop_windows.md"

    write_csv(rows, csv_path, overwrite=args.overwrite)
    write_json(rows, json_path, overwrite=args.overwrite)
    write_markdown(rows, md_path, overwrite=args.overwrite)

    print("\n[DONE] Wrote:")
    print(f"  CSV:  {csv_path}")
    print(f"  JSON: {json_path}")
    print(f"  MD:   {md_path}")

    print("\n[SUMMARY]")
    status_counts: dict[str, int] = {}
    for row in rows:
        status = row["crop_status"]
        status_counts[status] = status_counts.get(status, 0) + 1

    for status, count in sorted(status_counts.items()):
        print(f"  {status}: {count}")


if __name__ == "__main__":
    main()