#!/usr/bin/env python3
"""
Evaluate how proposed S2 crop windows affect final favela labels.

This script is a safety check before physically cropping S2/S1/label rasters.

Inputs:
- crop windows from 03_compute_s2_valid_crop_windows.py
- final binary label rasters

For each city, it computes:
- total positive label pixels before crop
- positive label pixels inside crop
- positive label pixels removed by crop
- percentage of positive label pixels removed
- whether the crop is safe from a label-preservation perspective

It does not modify any raster.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import rasterio
from rasterio.windows import Window


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate label-positive pixel loss caused by S2 crop windows."
    )

    parser.add_argument(
        "--crop-windows",
        type=str,
        required=True,
        help="CSV generated by 03_compute_s2_valid_crop_windows.py.",
    )

    parser.add_argument(
        "--labels-root",
        type=str,
        required=True,
        help=(
            "Root folder containing final labels, e.g. "
            "D:/post_processing_dataset/labels_final"
        ),
    )

    parser.add_argument(
        "--s2-root",
        type=str,
        default=None,
        help=(
            "Optional S2 root. If provided, the script checks that label and S2 "
            "rasters have matching dimensions/grid before using S2 crop windows."
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=str,
        required=True,
        help="Directory where label-impact reports will be written.",
    )

    parser.add_argument(
        "--cities",
        nargs="*",
        default=None,
        help="Optional list of city slugs. If omitted, all cities in crop-window CSV are processed.",
    )

    parser.add_argument(
        "--positive-threshold",
        type=float,
        default=0.5,
        help=(
            "Pixels with label value > this threshold are treated as positive. "
            "For binary uint8 labels, default 0.5 means value 1 is positive."
        ),
    )

    parser.add_argument(
        "--safe-loss-threshold-percent",
        type=float,
        default=0.0,
        help=(
            "Maximum allowed percentage of positive label pixels removed for status=safe. "
            "Default 0.0 means any positive label loss is flagged."
        ),
    )

    parser.add_argument(
        "--tiny-loss-threshold-percent",
        type=float,
        default=0.1,
        help=(
            "If positive label loss is above safe threshold but below this value, "
            "status becomes review_tiny_label_loss rather than unsafe_label_loss."
        ),
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing outputs.",
    )

    return parser.parse_args()


def percent(numerator: int | float, denominator: int | float) -> float:
    if denominator == 0:
        return 0.0
    return 100.0 * float(numerator) / float(denominator)


def find_label_raster(labels_root: Path, city: str) -> Path:
    city_dir = labels_root / city

    patterns = [
        f"{city}_label_final.tif",
        f"{city}_label*.tif",
        "*_label_final.tif",
        "*.tif",
    ]

    candidates: list[Path] = []

    if city_dir.exists():
        for pattern in patterns:
            candidates.extend(sorted(city_dir.glob(pattern)))

    if not candidates:
        for pattern in patterns:
            candidates.extend(sorted(labels_root.glob(pattern)))
            candidates.extend(sorted(labels_root.glob(f"*/{pattern}")))

    candidates = [p for p in candidates if p.is_file() and city in p.name]

    if not candidates:
        raise FileNotFoundError(f"No label raster found for city '{city}' under {labels_root}")

    exact = [p for p in candidates if p.name == f"{city}_label_final.tif"]
    if exact:
        return exact[0]

    return candidates[0]


def find_s2_raster(s2_root: Path, city: str) -> Path:
    city_dir = s2_root / city

    patterns = [
        f"{city}_s2_12bands_reflectance_10m.tif",
        f"{city}_s2*.tif",
        "*_s2_12bands_reflectance_10m.tif",
        "*.tif",
    ]

    candidates: list[Path] = []

    if city_dir.exists():
        for pattern in patterns:
            candidates.extend(sorted(city_dir.glob(pattern)))

    if not candidates:
        for pattern in patterns:
            candidates.extend(sorted(s2_root.glob(pattern)))
            candidates.extend(sorted(s2_root.glob(f"*/{pattern}")))

    candidates = [p for p in candidates if p.is_file() and city in p.name]

    if not candidates:
        raise FileNotFoundError(f"No S2 raster found for city '{city}' under {s2_root}")

    exact = [p for p in candidates if p.name == f"{city}_s2_12bands_reflectance_10m.tif"]
    if exact:
        return exact[0]

    return candidates[0]


def assert_crop_window_valid(
    row_start: int,
    row_stop: int,
    col_start: int,
    col_stop: int,
    height: int,
    width: int,
) -> None:
    if row_start < 0 or col_start < 0:
        raise ValueError("Crop window starts before raster origin.")

    if row_stop > height or col_stop > width:
        raise ValueError(
            f"Crop window exceeds raster bounds: "
            f"window rows[{row_start}:{row_stop}], cols[{col_start}:{col_stop}], "
            f"raster height={height}, width={width}"
        )

    if row_stop <= row_start or col_stop <= col_start:
        raise ValueError(
            f"Invalid empty crop window: rows[{row_start}:{row_stop}], cols[{col_start}:{col_stop}]"
        )


def check_s2_label_grid_alignment(label_path: Path, s2_path: Path) -> dict:
    """
    Check that label and S2 grids are compatible.

    For our purpose here, the crop-window pixel coordinates are valid for the
    label only if dimensions and transform match the original S2 raster.
    """
    with rasterio.open(label_path) as lab, rasterio.open(s2_path) as s2:
        same_width = lab.width == s2.width
        same_height = lab.height == s2.height
        same_crs = lab.crs == s2.crs
        same_transform = lab.transform.almost_equals(s2.transform)

        return {
            "s2_path": str(s2_path),
            "label_width": lab.width,
            "label_height": lab.height,
            "s2_width": s2.width,
            "s2_height": s2.height,
            "same_width": same_width,
            "same_height": same_height,
            "same_crs": same_crs,
            "same_transform": same_transform,
            "grid_alignment_ok": same_width and same_height and same_crs and same_transform,
        }


def count_positive_pixels_full(src: rasterio.io.DatasetReader, positive_threshold: float) -> int:
    total = 0

    for _, window in src.block_windows(1):
        data = src.read(1, window=window, masked=False)
        total += int(np.count_nonzero(data > positive_threshold))

    return total


def count_positive_pixels_window(
    src: rasterio.io.DatasetReader,
    row_start: int,
    row_stop: int,
    col_start: int,
    col_stop: int,
    positive_threshold: float,
) -> int:
    height = row_stop - row_start
    width = col_stop - col_start

    window = Window(
        col_off=col_start,
        row_off=row_start,
        width=width,
        height=height,
    )

    data = src.read(1, window=window, masked=False)
    return int(np.count_nonzero(data > positive_threshold))


def read_label_basic_stats(src: rasterio.io.DatasetReader) -> dict:
    """
    Collect lightweight label stats.

    We compute min/max and unique values only if the unique set remains small.
    This helps catch unexpected label values.
    """
    min_value = None
    max_value = None
    unique_values: set[int | float] = set()
    unique_overflow = False

    for _, window in src.block_windows(1):
        data = src.read(1, window=window, masked=False)

        if data.size == 0:
            continue

        block_min = float(np.nanmin(data))
        block_max = float(np.nanmax(data))

        if min_value is None or block_min < min_value:
            min_value = block_min
        if max_value is None or block_max > max_value:
            max_value = block_max

        if not unique_overflow:
            vals = np.unique(data)
            for v in vals:
                unique_values.add(float(v))
                if len(unique_values) > 20:
                    unique_overflow = True
                    unique_values.clear()
                    break

    if unique_overflow:
        unique_repr = "more_than_20_unique_values"
    else:
        unique_repr = ",".join(str(int(v)) if float(v).is_integer() else str(v) for v in sorted(unique_values))

    return {
        "label_min": min_value,
        "label_max": max_value,
        "label_unique_values_limited": unique_repr,
    }


def classify_label_crop_impact(
    removed_positive_pixels: int,
    removed_positive_percent: float,
    safe_loss_threshold_percent: float,
    tiny_loss_threshold_percent: float,
) -> tuple[str, str]:
    if removed_positive_pixels == 0:
        return "safe_no_positive_label_loss", "crop removes zero positive label pixels"

    if removed_positive_percent <= safe_loss_threshold_percent:
        return (
            "safe_within_threshold",
            f"positive label loss <= safe threshold {safe_loss_threshold_percent:.6f}%",
        )

    if removed_positive_percent <= tiny_loss_threshold_percent:
        return (
            "review_tiny_label_loss",
            f"positive label loss <= tiny-loss review threshold {tiny_loss_threshold_percent:.6f}%",
        )

    return (
        "unsafe_label_loss_review_crop",
        (
            f"positive label loss > tiny-loss threshold {tiny_loss_threshold_percent:.6f}%; "
            "review crop window before applying"
        ),
    )


def evaluate_city(
    city: str,
    crop_row: pd.Series,
    labels_root: Path,
    s2_root: Path | None,
    args: argparse.Namespace,
) -> dict:
    label_path = find_label_raster(labels_root, city)

    row_start = int(crop_row["row_start"])
    row_stop = int(crop_row["row_stop"])
    col_start = int(crop_row["col_start"])
    col_stop = int(crop_row["col_stop"])

    alignment_info = {
        "s2_path": "",
        "label_width": "",
        "label_height": "",
        "s2_width": "",
        "s2_height": "",
        "same_width": "",
        "same_height": "",
        "same_crs": "",
        "same_transform": "",
        "grid_alignment_ok": "",
    }

    if s2_root is not None:
        s2_path = find_s2_raster(s2_root, city)
        alignment_info = check_s2_label_grid_alignment(label_path, s2_path)

        if not alignment_info["grid_alignment_ok"]:
            raise ValueError(
                f"S2/label grid mismatch for {city}. "
                f"S2: {s2_path}; label: {label_path}; "
                f"alignment_info={alignment_info}"
            )

    with rasterio.open(label_path) as src:
        assert_crop_window_valid(
            row_start=row_start,
            row_stop=row_stop,
            col_start=col_start,
            col_stop=col_stop,
            height=src.height,
            width=src.width,
        )

        label_stats = read_label_basic_stats(src)

        positive_before = count_positive_pixels_full(
            src=src,
            positive_threshold=args.positive_threshold,
        )

        positive_inside = count_positive_pixels_window(
            src=src,
            row_start=row_start,
            row_stop=row_stop,
            col_start=col_start,
            col_stop=col_stop,
            positive_threshold=args.positive_threshold,
        )

        total_pixels_before = src.width * src.height
        crop_pixels = (row_stop - row_start) * (col_stop - col_start)

        label_width = src.width
        label_height = src.height
        label_crs = str(src.crs)
        label_transform = tuple(src.transform)
        label_dtype = src.dtypes[0]
        label_nodata = src.nodata

    positive_removed = positive_before - positive_inside
    positive_removed_percent = percent(positive_removed, positive_before)

    total_pixels_removed = total_pixels_before - crop_pixels
    total_pixels_removed_percent = percent(total_pixels_removed, total_pixels_before)

    positive_density_before_percent = percent(positive_before, total_pixels_before)
    positive_density_inside_crop_percent = percent(positive_inside, crop_pixels)

    impact_status, impact_reason = classify_label_crop_impact(
        removed_positive_pixels=positive_removed,
        removed_positive_percent=positive_removed_percent,
        safe_loss_threshold_percent=args.safe_loss_threshold_percent,
        tiny_loss_threshold_percent=args.tiny_loss_threshold_percent,
    )

    result = {
        "city": city,
        "crop_label_impact_status": impact_status,
        "impact_reason": impact_reason,
        "label_path": str(label_path),
        "row_start": row_start,
        "row_stop": row_stop,
        "col_start": col_start,
        "col_stop": col_stop,
        "label_width": label_width,
        "label_height": label_height,
        "label_dtype": label_dtype,
        "label_crs": label_crs,
        "label_nodata_value": label_nodata,
        "total_pixels_before_crop": total_pixels_before,
        "crop_pixels": crop_pixels,
        "total_pixels_removed_by_crop": total_pixels_removed,
        "total_pixels_removed_percent": total_pixels_removed_percent,
        "label_positive_pixels_before_crop": positive_before,
        "label_positive_pixels_inside_crop": positive_inside,
        "label_positive_pixels_removed_by_crop": positive_removed,
        "label_positive_removed_percent": positive_removed_percent,
        "positive_density_before_percent": positive_density_before_percent,
        "positive_density_inside_crop_percent": positive_density_inside_crop_percent,
        "positive_threshold": args.positive_threshold,
        "safe_loss_threshold_percent": args.safe_loss_threshold_percent,
        "tiny_loss_threshold_percent": args.tiny_loss_threshold_percent,
        "crop_status_from_03": crop_row.get("crop_status", ""),
        "recommended_action_from_plan": crop_row.get("recommended_action_from_plan", ""),
        "post_crop_s2_nodata_percent_from_03": crop_row.get(
            "post_crop_combined_nodata_percent_of_crop", ""
        ),
        "retained_pixels_percent_from_03": crop_row.get("retained_pixels_percent", ""),
        "removed_pixels_percent_from_03": crop_row.get("removed_pixels_percent", ""),
    }

    result.update(label_stats)
    result.update(alignment_info)

    return result


def write_csv(rows: list[dict], path: Path, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists. Use --overwrite to replace: {path}")

    if not rows:
        raise ValueError("No rows to write.")

    fieldnames = list(rows[0].keys())

    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_json(rows: list[dict], path: Path, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists. Use --overwrite to replace: {path}")

    with path.open("w", encoding="utf-8") as f:
        json.dump(rows, f, indent=2, ensure_ascii=False)


def write_markdown(rows: list[dict], path: Path, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists. Use --overwrite to replace: {path}")

    cols = [
        "city",
        "crop_label_impact_status",
        "label_positive_pixels_before_crop",
        "label_positive_pixels_inside_crop",
        "label_positive_pixels_removed_by_crop",
        "label_positive_removed_percent",
        "total_pixels_removed_percent",
        "post_crop_s2_nodata_percent_from_03",
        "impact_reason",
    ]

    with path.open("w", encoding="utf-8") as f:
        f.write("# Crop impact on final favela labels\n\n")
        f.write(
            "This report evaluates whether S2 crop windows remove positive "
            "favela label pixels. It does not modify rasters.\n\n"
        )

        f.write("## Status counts\n\n")
        status_counts: dict[str, int] = {}
        for row in rows:
            status = row["crop_label_impact_status"]
            status_counts[status] = status_counts.get(status, 0) + 1

        for status, count in sorted(status_counts.items()):
            f.write(f"- `{status}`: {count}\n")

        f.write("\n## City table\n\n")
        f.write("| " + " | ".join(cols) + " |\n")
        f.write("| " + " | ".join(["---"] * len(cols)) + " |\n")

        for row in rows:
            values = []
            for col in cols:
                value = row.get(col, "")
                if isinstance(value, float):
                    value = f"{value:.6f}"
                values.append(str(value).replace("|", "/"))
            f.write("| " + " | ".join(values) + " |\n")


def main() -> None:
    args = parse_args()

    crop_windows_path = Path(args.crop_windows)
    labels_root = Path(args.labels_root)
    output_dir = Path(args.output_dir)
    s2_root = Path(args.s2_root) if args.s2_root else None

    if not crop_windows_path.exists():
        raise FileNotFoundError(f"Crop windows CSV does not exist: {crop_windows_path}")

    if not labels_root.exists():
        raise FileNotFoundError(f"Labels root does not exist: {labels_root}")

    if s2_root is not None and not s2_root.exists():
        raise FileNotFoundError(f"S2 root does not exist: {s2_root}")

    output_dir.mkdir(parents=True, exist_ok=True)

    crop_df = pd.read_csv(crop_windows_path)

    required_cols = {"city", "row_start", "row_stop", "col_start", "col_stop"}
    missing = required_cols - set(crop_df.columns)
    if missing:
        raise ValueError(f"Crop windows CSV is missing required columns: {sorted(missing)}")

    if args.cities:
        crop_df = crop_df[crop_df["city"].isin(args.cities)].copy()

    if crop_df.empty:
        raise ValueError("No cities to process after filtering.")

    print(f"[INFO] Crop windows: {crop_windows_path}")
    print(f"[INFO] Labels root: {labels_root}")
    print(f"[INFO] S2 root: {s2_root if s2_root else 'not provided'}")
    print(f"[INFO] Output dir: {output_dir}")
    print(f"[INFO] Cities to process: {len(crop_df)}")
    print(f"[INFO] positive_threshold: {args.positive_threshold}")
    print(f"[INFO] safe_loss_threshold_percent: {args.safe_loss_threshold_percent}")
    print(f"[INFO] tiny_loss_threshold_percent: {args.tiny_loss_threshold_percent}")

    rows: list[dict] = []

    for i, crop_row in enumerate(crop_df.to_dict(orient="records"), start=1):
        city = str(crop_row["city"])
        print(f"\n[STEP {i}/{len(crop_df)}] {city}")

        try:
            result = evaluate_city(
                city=city,
                crop_row=pd.Series(crop_row),
                labels_root=labels_root,
                s2_root=s2_root,
                args=args,
            )
            rows.append(result)

            print(
                "[OK] "
                f"status={result['crop_label_impact_status']} | "
                f"positive_before={result['label_positive_pixels_before_crop']} | "
                f"positive_removed={result['label_positive_pixels_removed_by_crop']} | "
                f"removed_positive_pct={result['label_positive_removed_percent']:.6f}% | "
                f"total_area_removed={result['total_pixels_removed_percent']:.2f}%"
            )

        except Exception as exc:
            print(f"[ERROR] Failed city {city}: {exc}", file=sys.stderr)
            rows.append(
                {
                    "city": city,
                    "crop_label_impact_status": "error",
                    "impact_reason": str(exc),
                    "label_path": "",
                    "row_start": crop_row.get("row_start", ""),
                    "row_stop": crop_row.get("row_stop", ""),
                    "col_start": crop_row.get("col_start", ""),
                    "col_stop": crop_row.get("col_stop", ""),
                }
            )

    rows = sorted(rows, key=lambda x: str(x["city"]))

    csv_path = output_dir / "city_s2_crop_label_impact.csv"
    json_path = output_dir / "city_s2_crop_label_impact.json"
    md_path = output_dir / "city_s2_crop_label_impact.md"

    write_csv(rows, csv_path, overwrite=args.overwrite)
    write_json(rows, json_path, overwrite=args.overwrite)
    write_markdown(rows, md_path, overwrite=args.overwrite)

    print("\n[DONE] Wrote:")
    print(f"  CSV:  {csv_path}")
    print(f"  JSON: {json_path}")
    print(f"  MD:   {md_path}")

    print("\n[SUMMARY]")
    status_counts: dict[str, int] = {}
    for row in rows:
        status = row["crop_label_impact_status"]
        status_counts[status] = status_counts.get(status, 0) + 1

    for status, count in sorted(status_counts.items()):
        print(f"  {status}: {count}")


if __name__ == "__main__":
    main()