#!/usr/bin/env python3
"""
Apply valid crop windows to S2, S1 SNAP, and final label rasters.

This creates a new cropped dataset instance where border-connected S2 nodata
has been removed according to crop windows computed by:

    03_compute_s2_valid_crop_windows.py

Important:
- This script physically writes new rasters.
- It applies the exact same pixel window to S2, S1, and labels.
- It does not fill remaining internal S2 nodata.
- It creates a crop-based repaired instance, so label loss must be documented.
"""

from __future__ import annotations

import argparse
import csv
import json
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import rasterio
from rasterio.windows import Window


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Apply valid crop windows to aligned S2, S1 SNAP, and label rasters."
    )

    parser.add_argument(
        "--crop-windows",
        type=str,
        required=True,
        help="CSV generated by 03_compute_s2_valid_crop_windows.py.",
    )

    parser.add_argument(
        "--s2-root",
        type=str,
        required=True,
        help="Input S2 root, e.g. D:/post_processing_dataset/dataset_instances/instance_B_standard_rs/s2",
    )

    parser.add_argument(
        "--s1-root",
        type=str,
        required=True,
        help="Input S1 SNAP root, e.g. D:/post_processing_dataset/dataset_instances/instance_B_standard_rs/s1_snap",
    )

    parser.add_argument(
        "--labels-root",
        type=str,
        required=True,
        help="Input labels root, e.g. D:/post_processing_dataset/labels_final",
    )

    parser.add_argument(
        "--output-root",
        type=str,
        required=True,
        help=(
            "Output instance root, e.g. "
            "D:/post_processing_dataset/dataset_instances/instance_C_s2_nodata_repaired"
        ),
    )

    parser.add_argument(
        "--cities",
        nargs="*",
        default=None,
        help="Optional city list. If omitted, all cities in crop-window CSV are processed.",
    )

    parser.add_argument(
        "--tile-size",
        type=int,
        default=512,
        help="Chunk size for block-wise raster copying.",
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing output rasters.",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only print planned operations; do not write files.",
    )

    return parser.parse_args()


def find_s2_raster(root: Path, city: str) -> Path:
    patterns = [
        root / city / f"{city}_s2_12bands_reflectance_10m.tif",
        root / city / f"{city}_s2*.tif",
        root / f"{city}_s2_12bands_reflectance_10m.tif",
    ]

    candidates: list[Path] = []

    for pattern in patterns:
        if "*" in str(pattern):
            candidates.extend(sorted(pattern.parent.glob(pattern.name)))
        elif pattern.exists():
            candidates.append(pattern)

    candidates = [p for p in candidates if p.is_file() and city in p.name]

    if not candidates:
        raise FileNotFoundError(f"No S2 raster found for {city} under {root}")

    exact = [p for p in candidates if p.name == f"{city}_s2_12bands_reflectance_10m.tif"]
    return exact[0] if exact else candidates[0]


def find_s1_raster(root: Path, city: str) -> Path:
    patterns = [
        root / city / f"{city}_s1_snap_vv_vh_vvdiff_10m_aligned.tif",
        root / city / f"{city}_s1*.tif",
        root / f"{city}_s1_snap_vv_vh_vvdiff_10m_aligned.tif",
    ]

    candidates: list[Path] = []

    for pattern in patterns:
        if "*" in str(pattern):
            candidates.extend(sorted(pattern.parent.glob(pattern.name)))
        elif pattern.exists():
            candidates.append(pattern)

    candidates = [p for p in candidates if p.is_file() and city in p.name]

    if not candidates:
        raise FileNotFoundError(f"No S1 SNAP raster found for {city} under {root}")

    exact = [p for p in candidates if p.name == f"{city}_s1_snap_vv_vh_vvdiff_10m_aligned.tif"]
    return exact[0] if exact else candidates[0]


def find_label_raster(root: Path, city: str) -> Path:
    patterns = [
        root / city / f"{city}_label_final.tif",
        root / city / f"{city}_label*.tif",
        root / f"{city}_label_final.tif",
    ]

    candidates: list[Path] = []

    for pattern in patterns:
        if "*" in str(pattern):
            candidates.extend(sorted(pattern.parent.glob(pattern.name)))
        elif pattern.exists():
            candidates.append(pattern)

    candidates = [p for p in candidates if p.is_file() and city in p.name]

    if not candidates:
        raise FileNotFoundError(f"No label raster found for {city} under {root}")

    exact = [p for p in candidates if p.name == f"{city}_label_final.tif"]
    return exact[0] if exact else candidates[0]


def check_same_grid(reference_path: Path, other_path: Path, name: str) -> dict:
    with rasterio.open(reference_path) as ref, rasterio.open(other_path) as other:
        same_width = ref.width == other.width
        same_height = ref.height == other.height
        same_crs = ref.crs == other.crs
        same_transform = ref.transform.almost_equals(other.transform)

        ok = same_width and same_height and same_crs and same_transform

        info = {
            f"{name}_same_width": same_width,
            f"{name}_same_height": same_height,
            f"{name}_same_crs": same_crs,
            f"{name}_same_transform": same_transform,
            f"{name}_grid_ok": ok,
        }

        if not ok:
            raise ValueError(
                f"Grid mismatch between reference S2 and {name}.\n"
                f"Reference: {reference_path}\n"
                f"Other: {other_path}\n"
                f"Info: {info}"
            )

        return info


def validate_window(
    row_start: int,
    row_stop: int,
    col_start: int,
    col_stop: int,
    height: int,
    width: int,
) -> None:
    if row_start < 0 or col_start < 0:
        raise ValueError("Crop window starts outside raster.")

    if row_stop > height or col_stop > width:
        raise ValueError(
            f"Crop window exceeds raster bounds: "
            f"rows[{row_start}:{row_stop}], cols[{col_start}:{col_stop}], "
            f"raster height={height}, width={width}"
        )

    if row_stop <= row_start or col_stop <= col_start:
        raise ValueError(
            f"Invalid empty crop window: rows[{row_start}:{row_stop}], cols[{col_start}:{col_stop}]"
        )


def iter_output_tiles(height: int, width: int, tile_size: int):
    for row_off in range(0, height, tile_size):
        h = min(tile_size, height - row_off)
        for col_off in range(0, width, tile_size):
            w = min(tile_size, width - col_off)
            yield Window(col_off=col_off, row_off=row_off, width=w, height=h)


def make_output_profile(
    src: rasterio.io.DatasetReader,
    crop_window: Window,
    output_height: int,
    output_width: int,
    kind: str,
) -> dict:
    profile = src.profile.copy()
    profile.update(
        {
            "height": output_height,
            "width": output_width,
            "transform": src.window_transform(crop_window),
            "driver": "GTiff",
            "compress": "deflate",
            "predictor": 2 if np.issubdtype(np.dtype(src.dtypes[0]), np.floating) else 1,
            "tiled": True,
            "blockxsize": 512,
            "blockysize": 512,
            "BIGTIFF": "IF_SAFER",
        }
    )

    # Important: label 0 is background, not nodata.
    # If the source label accidentally has nodata=0, remove it in the repaired instance.
    if kind == "label":
        profile["nodata"] = None

    return profile


def copy_crop_raster(
    src_path: Path,
    dst_path: Path,
    row_start: int,
    row_stop: int,
    col_start: int,
    col_stop: int,
    kind: str,
    tile_size: int,
    overwrite: bool,
    dry_run: bool,
) -> dict:
    if dst_path.exists():
        if overwrite:
            if not dry_run:
                dst_path.unlink()
        else:
            raise FileExistsError(f"Output exists. Use --overwrite to replace: {dst_path}")

    dst_path.parent.mkdir(parents=True, exist_ok=True)

    with rasterio.open(src_path) as src:
        validate_window(
            row_start=row_start,
            row_stop=row_stop,
            col_start=col_start,
            col_stop=col_stop,
            height=src.height,
            width=src.width,
        )

        output_height = row_stop - row_start
        output_width = col_stop - col_start
        crop_window = Window(
            col_off=col_start,
            row_off=row_start,
            width=output_width,
            height=output_height,
        )

        profile = make_output_profile(
            src=src,
            crop_window=crop_window,
            output_height=output_height,
            output_width=output_width,
            kind=kind,
        )

        descriptions = src.descriptions
        tags = src.tags()

        if dry_run:
            return {
                f"{kind}_src_path": str(src_path),
                f"{kind}_dst_path": str(dst_path),
                f"{kind}_width": output_width,
                f"{kind}_height": output_height,
                f"{kind}_band_count": src.count,
                f"{kind}_dtype": src.dtypes[0],
                f"{kind}_written": False,
            }

        with rasterio.open(dst_path, "w", **profile) as dst:
            for out_window in iter_output_tiles(output_height, output_width, tile_size):
                source_window = Window(
                    col_off=col_start + int(out_window.col_off),
                    row_off=row_start + int(out_window.row_off),
                    width=int(out_window.width),
                    height=int(out_window.height),
                )

                data = src.read(window=source_window)
                dst.write(data, window=out_window)

            # Preserve a sensible valid-data mask.
            # For S2/S1: valid only where all bands are valid in the source.
            # For labels: all pixels are valid because 0 is background.
            if kind == "label":
                dst.write_mask(np.full((output_height, output_width), 255, dtype=np.uint8))
            else:
                full_mask = np.zeros((output_height, output_width), dtype=np.uint8)

                for out_window in iter_output_tiles(output_height, output_width, tile_size):
                    source_window = Window(
                        col_off=col_start + int(out_window.col_off),
                        row_off=row_start + int(out_window.row_off),
                        width=int(out_window.width),
                        height=int(out_window.height),
                    )

                    masks = src.read_masks(window=source_window)
                    valid = np.all(masks > 0, axis=0).astype(np.uint8) * 255

                    r0 = int(out_window.row_off)
                    r1 = r0 + int(out_window.height)
                    c0 = int(out_window.col_off)
                    c1 = c0 + int(out_window.width)

                    full_mask[r0:r1, c0:c1] = valid

                dst.write_mask(full_mask)

            for band_idx, desc in enumerate(descriptions, start=1):
                if desc:
                    dst.set_band_description(band_idx, desc)

            dst.update_tags(**tags)
            dst.update_tags(
                crop_source_path=str(src_path),
                crop_row_start=row_start,
                crop_row_stop=row_stop,
                crop_col_start=col_start,
                crop_col_stop=col_stop,
                crop_kind=kind,
            )

    return {
        f"{kind}_src_path": str(src_path),
        f"{kind}_dst_path": str(dst_path),
        f"{kind}_width": output_width,
        f"{kind}_height": output_height,
        f"{kind}_band_count": profile["count"],
        f"{kind}_dtype": profile["dtype"],
        f"{kind}_written": True,
    }


def count_label_positive(label_path: Path, threshold: float = 0.5) -> int:
    total = 0
    with rasterio.open(label_path) as src:
        for _, window in src.block_windows(1):
            data = src.read(1, window=window)
            total += int(np.count_nonzero(data > threshold))
    return total


def check_output_alignment(s2_out: Path, s1_out: Path, label_out: Path) -> dict:
    with rasterio.open(s2_out) as s2, rasterio.open(s1_out) as s1, rasterio.open(label_out) as lab:
        same_s1 = (
            s2.width == s1.width
            and s2.height == s1.height
            and s2.crs == s1.crs
            and s2.transform.almost_equals(s1.transform)
        )

        same_label = (
            s2.width == lab.width
            and s2.height == lab.height
            and s2.crs == lab.crs
            and s2.transform.almost_equals(lab.transform)
        )

        if not same_s1 or not same_label:
            raise ValueError(
                f"Output alignment failed:\n"
                f"S2: {s2_out}\n"
                f"S1: {s1_out}\n"
                f"Label: {label_out}\n"
                f"same_s1={same_s1}, same_label={same_label}"
            )

        return {
            "output_alignment_s1_ok": same_s1,
            "output_alignment_label_ok": same_label,
            "output_width": s2.width,
            "output_height": s2.height,
            "output_crs": str(s2.crs),
            "output_transform": tuple(s2.transform),
        }


def write_csv(rows: list[dict], path: Path, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists. Use --overwrite to replace: {path}")

    all_fields = []
    seen = set()

    for row in rows:
        for key in row.keys():
            if key not in seen:
                seen.add(key)
                all_fields.append(key)

    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=all_fields)
        writer.writeheader()
        writer.writerows(rows)


def write_json(rows: list[dict], path: Path, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists. Use --overwrite to replace: {path}")

    with path.open("w", encoding="utf-8") as f:
        json.dump(rows, f, indent=2, ensure_ascii=False)


def main() -> None:
    args = parse_args()

    crop_windows_path = Path(args.crop_windows)
    s2_root = Path(args.s2_root)
    s1_root = Path(args.s1_root)
    labels_root = Path(args.labels_root)
    output_root = Path(args.output_root)

    for p, name in [
        (crop_windows_path, "crop windows CSV"),
        (s2_root, "S2 root"),
        (s1_root, "S1 root"),
        (labels_root, "labels root"),
    ]:
        if not p.exists():
            raise FileNotFoundError(f"{name} does not exist: {p}")

    crop_df = pd.read_csv(crop_windows_path)

    required_cols = {"city", "row_start", "row_stop", "col_start", "col_stop"}
    missing = required_cols - set(crop_df.columns)
    if missing:
        raise ValueError(f"Crop windows CSV is missing columns: {sorted(missing)}")

    if args.cities:
        crop_df = crop_df[crop_df["city"].isin(args.cities)].copy()

    if crop_df.empty:
        raise ValueError("No cities to process.")

    print(f"[INFO] Crop windows: {crop_windows_path}")
    print(f"[INFO] S2 root: {s2_root}")
    print(f"[INFO] S1 root: {s1_root}")
    print(f"[INFO] Labels root: {labels_root}")
    print(f"[INFO] Output root: {output_root}")
    print(f"[INFO] Cities to process: {len(crop_df)}")
    print(f"[INFO] tile_size: {args.tile_size}")
    print(f"[INFO] overwrite: {args.overwrite}")
    print(f"[INFO] dry_run: {args.dry_run}")

    if not args.dry_run:
        output_root.mkdir(parents=True, exist_ok=True)
        (output_root / "s2").mkdir(exist_ok=True)
        (output_root / "s1_snap").mkdir(exist_ok=True)
        (output_root / "labels").mkdir(exist_ok=True)
        (output_root / "metadata").mkdir(exist_ok=True)
        (output_root / "qc").mkdir(exist_ok=True)

    rows: list[dict] = []

    for i, crop_row in enumerate(crop_df.to_dict(orient="records"), start=1):
        city = str(crop_row["city"])

        row_start = int(crop_row["row_start"])
        row_stop = int(crop_row["row_stop"])
        col_start = int(crop_row["col_start"])
        col_stop = int(crop_row["col_stop"])

        print(f"\n[STEP {i}/{len(crop_df)}] {city}")
        print(f"[INFO] crop rows[{row_start}:{row_stop}], cols[{col_start}:{col_stop}]")

        try:
            s2_path = find_s2_raster(s2_root, city)
            s1_path = find_s1_raster(s1_root, city)
            label_path = find_label_raster(labels_root, city)

            print(f"[INFO] S2:    {s2_path}")
            print(f"[INFO] S1:    {s1_path}")
            print(f"[INFO] Label: {label_path}")

            grid_s1 = check_same_grid(s2_path, s1_path, "s1")
            grid_label = check_same_grid(s2_path, label_path, "label")

            s2_out = output_root / "s2" / city / s2_path.name
            s1_out = output_root / "s1_snap" / city / s1_path.name
            label_out = output_root / "labels" / city / label_path.name

            label_positive_before = count_label_positive(label_path)

            s2_info = copy_crop_raster(
                src_path=s2_path,
                dst_path=s2_out,
                row_start=row_start,
                row_stop=row_stop,
                col_start=col_start,
                col_stop=col_stop,
                kind="s2",
                tile_size=args.tile_size,
                overwrite=args.overwrite,
                dry_run=args.dry_run,
            )

            s1_info = copy_crop_raster(
                src_path=s1_path,
                dst_path=s1_out,
                row_start=row_start,
                row_stop=row_stop,
                col_start=col_start,
                col_stop=col_stop,
                kind="s1",
                tile_size=args.tile_size,
                overwrite=args.overwrite,
                dry_run=args.dry_run,
            )

            label_info = copy_crop_raster(
                src_path=label_path,
                dst_path=label_out,
                row_start=row_start,
                row_stop=row_stop,
                col_start=col_start,
                col_stop=col_stop,
                kind="label",
                tile_size=args.tile_size,
                overwrite=args.overwrite,
                dry_run=args.dry_run,
            )

            if args.dry_run:
                alignment_info = {
                    "output_alignment_s1_ok": "",
                    "output_alignment_label_ok": "",
                    "output_width": row_stop - row_start,
                    "output_height": col_stop - col_start,
                    "output_crs": "",
                    "output_transform": "",
                }
                label_positive_after = ""
            else:
                alignment_info = check_output_alignment(s2_out, s1_out, label_out)
                label_positive_after = count_label_positive(label_out)

            label_positive_removed = (
                "" if label_positive_after == "" else label_positive_before - int(label_positive_after)
            )
            label_positive_removed_percent = (
                ""
                if label_positive_after == "" or label_positive_before == 0
                else 100.0 * label_positive_removed / label_positive_before
            )

            result = {
                "city": city,
                "status": "ok",
                "row_start": row_start,
                "row_stop": row_stop,
                "col_start": col_start,
                "col_stop": col_stop,
                "crop_status_from_03": crop_row.get("crop_status", ""),
                "recommended_action_from_plan": crop_row.get("recommended_action_from_plan", ""),
                "pre_crop_s2_nodata_percent_from_03": crop_row.get("pre_combined_nodata_percent", ""),
                "post_crop_s2_nodata_percent_from_03": crop_row.get(
                    "post_crop_combined_nodata_percent_of_crop", ""
                ),
                "retained_pixels_percent_from_03": crop_row.get("retained_pixels_percent", ""),
                "removed_pixels_percent_from_03": crop_row.get("removed_pixels_percent", ""),
                "label_positive_before_crop": label_positive_before,
                "label_positive_after_crop": label_positive_after,
                "label_positive_removed_by_crop": label_positive_removed,
                "label_positive_removed_percent": label_positive_removed_percent,
                "dry_run": args.dry_run,
            }

            result.update(grid_s1)
            result.update(grid_label)
            result.update(s2_info)
            result.update(s1_info)
            result.update(label_info)
            result.update(alignment_info)

            rows.append(result)

            print(
                "[OK] wrote cropped aligned rasters | "
                f"output_size={result['output_width']}x{result['output_height']} | "
                f"label_removed={label_positive_removed_percent if label_positive_removed_percent != '' else 'NA'}%"
            )

        except Exception as exc:
            print(f"[ERROR] {city}: {exc}")
            rows.append(
                {
                    "city": city,
                    "status": "error",
                    "error": str(exc),
                    "row_start": row_start,
                    "row_stop": row_stop,
                    "col_start": col_start,
                    "col_stop": col_stop,
                    "dry_run": args.dry_run,
                }
            )

    metadata_dir = output_root / "metadata"
    qc_dir = output_root / "qc"

    if args.dry_run:
        metadata_dir = output_root
        qc_dir = output_root
    else:
        metadata_dir.mkdir(parents=True, exist_ok=True)
        qc_dir.mkdir(parents=True, exist_ok=True)

    csv_path = metadata_dir / "instance_C_crop_application_summary.csv"
    json_path = metadata_dir / "instance_C_crop_application_summary.json"

    write_csv(rows, csv_path, overwrite=args.overwrite)
    write_json(rows, json_path, overwrite=args.overwrite)

    print("\n[DONE] Wrote:")
    print(f"  CSV:  {csv_path}")
    print(f"  JSON: {json_path}")

    print("\n[SUMMARY]")
    status_counts: dict[str, int] = {}
    for row in rows:
        status = row["status"]
        status_counts[status] = status_counts.get(status, 0) + 1

    for status, count in sorted(status_counts.items()):
        print(f"  {status}: {count}")


if __name__ == "__main__":
    main()